import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg=window.A2C_CONFIG||{};
const configured=/^https:\/\/.+\.supabase\.co$/.test(cfg.SUPABASE_URL||'')&&!String(cfg.SUPABASE_ANON_KEY||'').startsWith('TU_');
const sb=configured?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const app=document.querySelector('#app');
const state={session:null,user:null,profile:null,permissions:null,piggies:[],transactions:[],folders:[],goals:[],contributions:[],notifications:[],users:[],tab:'piggies',channel:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=c=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100);
const cents=v=>{let s=String(v||'0').trim().replace(/\s|€/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Math.round(Number(s)*100)};
const dateFmt=v=>v?new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:v.includes?.('T')?'short':undefined}).format(new Date(v)):'';
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg,bad=false){const el=document.querySelector('#toast');el.textContent=msg;el.style.borderColor=bad?'var(--red)':'var(--line)';el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function err(error){console.error(error);toast(error?.message||'Ha ocurrido un error',true)}
function loading(btn,on=true){if(!btn)return;btn.disabled=on;btn.dataset.label??=btn.textContent;btn.textContent=on?'Procesando…':btn.dataset.label}

if(!configured) renderSetup(); else boot();
async function boot(){const {data}=await sb.auth.getSession();state.session=data.session;state.user=data.session?.user||null;if(state.user)await enter();else renderAuth();sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.user=session?.user||null;if(state.user&&!state.profile)await enter();if(!state.user){cleanupRealtime();Object.assign(state,{profile:null,permissions:null});renderAuth();}})}

function renderSetup(){app.innerHTML=`<section class="auth-shell"><div class="auth-card"><div class="brand"><div class="brand-mark">A2C</div><div><h1>A2C Finanzas</h1><p>Configuración inicial</p></div></div><h2>Conecta Supabase</h2><p class="muted">Edita <strong>config.js</strong> y sustituye los dos valores de ejemplo por la URL y la clave pública de tu proyecto Supabase.</p><div class="list-row"><div><div class="list-title">SUPABASE_URL</div><div class="list-meta">https://…supabase.co</div></div></div><div class="list-row"><div><div class="list-title">SUPABASE_ANON_KEY</div><div class="list-meta">Clave anon o publishable; nunca service_role</div></div></div></div></section>`}
function renderAuth(){app.innerHTML=`<section class="auth-shell"><form class="auth-card" id="auth-form"><div class="brand"><div class="brand-mark">A2C</div><div><h1>A2C Finanzas</h1><p>Acceso privado</p></div></div><h2>Iniciar sesión</h2><p class="muted">Introduce el email y la contraseña que te ha proporcionado el administrador. No existe registro público.</p><div class="field"><label>Email</label><input id="auth-email" type="email" autocomplete="username" required placeholder="tu@email.com"></div><div class="field"><label>Contraseña</label><input id="auth-password" type="password" autocomplete="current-password" minlength="8" required placeholder="••••••••"></div><button class="btn primary full">Entrar</button></form></section>`;document.querySelector('#auth-form').addEventListener('submit',signInPassword)}
async function signInPassword(e){e.preventDefault();const btn=e.submitter,email=document.querySelector('#auth-email').value.trim().toLowerCase(),password=document.querySelector('#auth-password').value;loading(btn);const {error}=await sb.auth.signInWithPassword({email,password});loading(btn,false);if(error)return err(new Error('Email o contraseña incorrectos'))}

async function enter(){try{const [{data:profile,error:pe},{data:perm,error:pme}]=await Promise.all([sb.from('profiles').select('*').eq('id',state.user.id).single(),sb.from('user_permissions').select('*').eq('user_id',state.user.id).single()]);if(pe)throw pe;if(pme)throw pme;if(!profile.active){await sb.auth.signOut();throw new Error('Tu usuario está desactivado. Contacta con el administrador.')}state.profile=profile;state.permissions=perm;await refreshAll();subscribeRealtime();renderShell();}catch(e){err(e);renderAuth()}}
async function refreshAll(){const queries=[sb.from('piggy_banks').select('*,piggy_members(user_id,role,can_add_income,can_add_expense,profiles(display_name,email))').order('created_at',{ascending:false}),sb.from('piggy_transactions').select('*,profiles(display_name,email)').order('created_at',{ascending:false}),sb.from('folders').select('*').order('created_at',{ascending:false}),sb.from('goals').select('*').order('created_at',{ascending:false}),sb.from('goal_contributions').select('*').order('created_at',{ascending:false}),sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100)];if(state.profile?.role==='admin')queries.push(sb.from('profiles').select('*,user_permissions(*)').order('created_at'));const results=await Promise.all(queries);results.forEach(r=>{if(r.error)throw r.error});[state.piggies,state.transactions,state.folders,state.goals,state.contributions,state.notifications]=results.slice(0,6).map(r=>r.data||[]);state.users=results[6]?.data||[]}
function subscribeRealtime(){cleanupRealtime();state.channel=sb.channel('a2c-live-'+state.user.id).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${state.user.id}`},async()=>{await refreshLight();renderShell();toast('Nueva notificación')}).on('postgres_changes',{event:'*',schema:'public',table:'piggy_transactions'},async()=>{await refreshLight();renderShell()}).subscribe()}
function cleanupRealtime(){if(state.channel&&sb)sb.removeChannel(state.channel);state.channel=null}
async function refreshLight(){const rs=await Promise.all([sb.from('piggy_banks').select('*,piggy_members(user_id,role,can_add_income,can_add_expense,profiles(display_name,email))').order('created_at',{ascending:false}),sb.from('piggy_transactions').select('*,profiles(display_name,email)').order('created_at',{ascending:false}),sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100)]);if(rs.some(x=>x.error))return;[state.piggies,state.transactions,state.notifications]=rs.map(x=>x.data||[])}

function renderShell(){const unread=state.notifications.filter(n=>!n.read_at).length;app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">A2C</div><div><h1>A2C Finanzas</h1><p>${esc(state.profile.display_name||state.profile.email)}</p></div></div><div class="top-actions"><button class="icon-btn" data-tab="notifications" aria-label="Notificaciones">🔔${unread?`<i class="badge">${unread}</i>`:''}</button><button class="icon-btn" id="logout" aria-label="Salir">↪</button></div></header><div id="view">${renderView()}</div><nav class="bottom-nav">${nav('piggies','🏦','Huchas')}${nav('folders','📁','Carpetas')}${nav('goals','🎯','Objetivos')}${nav('activity','↕','Actividad')}${nav('notifications','🔔','Avisos')}${state.profile.role==='admin'?nav('admin','⚙','Admin'):nav('profile','👤','Perfil')}</nav></div>`;bindShell()}
function nav(tab,icon,label){return `<button class="nav-btn ${state.tab===tab?'active':''}" data-tab="${tab}"><span>${icon}</span>${label}</button>`}
function renderView(){if(state.tab==='piggies')return renderPiggies();if(state.tab==='folders')return renderFolders();if(state.tab==='goals')return renderGoals();if(state.tab==='activity')return renderActivity();if(state.tab==='notifications')return renderNotifications();if(state.tab==='admin')return renderAdmin();return renderProfile()}
function piggyStats(id){const list=state.transactions.filter(t=>t.piggy_id===id),income=list.filter(t=>t.kind==='income').reduce((s,t)=>s+Number(t.amount_cents),0),expense=list.filter(t=>t.kind==='expense').reduce((s,t)=>s+Number(t.amount_cents),0);return{list,income,expense,balance:income-expense}}
function renderPiggies(){const total=state.piggies.reduce((s,p)=>s+piggyStats(p.id).balance,0);return `<section class="hero"><div class="hero-card"><div class="kicker">Saldo total en huchas</div><div class="hero-value">${money(total)}</div><div class="hero-sub">Cuentas personales y compartidas</div></div><div class="stat-grid"><div class="stat-card"><span class="kicker">Huchas</span><strong>${state.piggies.length}</strong></div><div class="stat-card"><span class="kicker">Compartidas</span><strong>${state.piggies.filter(p=>p.is_shared).length}</strong></div></div></section><div class="section-head"><div><h2>Huchas</h2><p>Solo contienen ingresos y gastos; nunca objetivos.</p></div>${state.permissions.can_create_piggy?'<button class="btn primary" data-open="piggy">Nueva hucha</button>':''}</div><div class="card-grid">${state.piggies.length?state.piggies.map(p=>piggyCard(p)).join(''):'<div class="empty">Aún no tienes huchas.</div>'}</div>`}
function piggyCard(p){const s=piggyStats(p.id);return `<article class="entity-card" style="--accent:${esc(p.color)}"><button class="entity-menu" data-menu-piggy="${p.id}">•••</button><div class="entity-top"><div class="emoji">${esc(p.emoji)}</div><div><div class="entity-name">${esc(p.name)}</div><div class="entity-type">${p.is_shared?'Hucha conjunta · '+p.piggy_members.length+' miembros':'Hucha personal'}</div></div></div><div class="balance-box"><span>Saldo disponible</span><strong>${money(s.balance)}</strong></div><div class="minis"><div class="mini"><span>Ingresos</span><strong class="positive">${money(s.income)}</strong></div><div class="mini"><span>Gastos</span><strong class="negative">${money(s.expense)}</strong></div></div></article>`}
function renderFolders(){return `<div class="section-head"><div><h2>Carpetas</h2><p>Ordenan referencias y movimientos. No contienen objetivos ni ahorro.</p></div><button class="btn primary" data-open="folder">Nueva carpeta</button></div><div class="card-grid">${state.folders.length?state.folders.map(f=>`<article class="entity-card" style="--accent:#4f8cff"><button class="entity-menu" data-delete-folder="${f.id}">×</button><div class="entity-top"><div class="emoji">${esc(f.emoji)}</div><div><div class="entity-name">${esc(f.name)}</div><div class="entity-type">Carpeta organizativa</div></div></div><div class="balance-box"><span>Función</span><strong style="font-size:15px">Organizar gastos e ingresos</strong></div></article>`).join(''):'<div class="empty">Crea carpetas para organizar tus conceptos.</div>'}</div>`}
function goalSaved(id){return state.contributions.filter(c=>c.goal_id===id).reduce((s,c)=>s+Number(c.amount_cents),0)}
function renderGoals(){return `<div class="section-head"><div><h2>Objetivos</h2><p>Metas exclusivas de ahorro con importe y fecha.</p></div><button class="btn primary" data-open="goal">Nuevo objetivo</button></div><div class="card-grid">${state.goals.length?state.goals.map(g=>{const saved=goalSaved(g.id),pct=Math.min(100,Math.round(saved/Number(g.target_cents)*100));return `<article class="entity-card" style="--accent:#ffbd59"><button class="entity-menu" data-menu-goal="${g.id}">•••</button><div class="entity-top"><div class="emoji">${esc(g.emoji)}</div><div><div class="entity-name">${esc(g.name)}</div><div class="entity-type">${g.target_date?'Límite '+dateFmt(g.target_date):'Sin fecha límite'}</div></div></div><div class="balance-box"><span>Ahorrado</span><strong>${money(saved)}</strong><div class="progress"><i style="width:${pct}%"></i></div></div><div class="minis"><div class="mini"><span>Meta</span><strong>${money(g.target_cents)}</strong></div><div class="mini"><span>Falta</span><strong>${money(Math.max(0,g.target_cents-saved))}</strong></div></div></article>`}).join(''):'<div class="empty">Crea tu primer objetivo de ahorro.</div>'}</div>`}
function renderActivity(){const rows=state.transactions.slice(0,100);return `<div class="section-head"><div><h2>Actividad conjunta</h2><p>Registro de ingresos y gastos de huchas accesibles.</p></div></div><div class="list">${rows.length?rows.map(t=>{const p=state.piggies.find(x=>x.id===t.piggy_id);return `<div class="list-row"><div class="list-main"><div class="list-title">${esc(t.concept)}</div><div class="list-meta">${esc(p?.name||'Hucha')} · ${esc(t.profiles?.display_name||t.profiles?.email||'Usuario')} · ${dateFmt(t.occurred_on)}</div></div><strong class="${t.kind==='income'?'positive':'negative'}">${t.kind==='income'?'+':'−'}${money(t.amount_cents)}</strong></div>`}).join(''):'<div class="empty">No hay movimientos.</div>'}</div>`}
function renderNotifications(){return `<div class="section-head"><div><h2>Notificaciones</h2><p>${state.notifications.filter(n=>!n.read_at).length} sin leer</p></div>${state.notifications.some(n=>!n.read_at)?'<button class="btn" id="read-all">Marcar todas</button>':''}</div><div class="list">${state.notifications.length?state.notifications.map(n=>`<button class="list-row ${n.read_at?'':'unread'}" data-read="${n.id}"><div class="list-main" style="text-align:left"><div class="list-title">${esc(n.title)}</div><div class="list-meta">${esc(n.body)} · ${dateFmt(n.created_at)}</div></div>${n.read_at?'':'<span class="pill">Nueva</span>'}</button>`).join(''):'<div class="empty">No hay notificaciones.</div>'}</div>`}
function renderProfile(){return `<div class="section-head"><div><h2>Mi perfil</h2><p>Datos de la cuenta y permisos concedidos.</p></div></div><div class="panel" style="padding:20px;border-radius:24px"><div class="list-title">${esc(state.profile.display_name||state.profile.email)}</div><div class="list-meta">${esc(state.profile.email)}</div><div class="permission-grid">${permissionLabels(state.permissions).map(x=>`<span class="pill">${x}</span>`).join('')}</div></div>`}
function permissionLabels(p){return[['can_create_piggy','Crear huchas'],['can_create_shared','Crear compartidas'],['can_add_income','Añadir fondos'],['can_add_expense','Registrar gastos'],['can_manage_members','Gestionar miembros']].filter(([k])=>p?.[k]).map(x=>x[1])}
function renderAdmin(){return `<div class="section-head"><div><h2>Administración</h2><p>Crea las cuentas, asigna contraseñas y concede permisos.</p></div><button class="btn primary" id="create-user">Nuevo usuario</button></div><div class="admin-table">${state.users.map(u=>{const p=u.user_permissions?.[0]||{};return `<article class="user-card" data-user-card="${u.id}"><div class="list-row"><div><div class="list-title">${esc(u.display_name||u.email)}</div><div class="list-meta">${esc(u.email)}</div></div><select data-admin-role><option value="user" ${u.role==='user'?'selected':''}>Usuario</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrador</option></select></div><div class="permission-grid">${[['active','Activo',u],['can_create_piggy','Crear huchas',p],['can_create_shared','Crear compartidas',p],['can_add_income','Añadir fondos',p],['can_add_expense','Registrar gastos',p],['can_manage_members','Gestionar miembros',p]].map(([k,l,o])=>`<label class="check"><input type="checkbox" data-perm="${k}" ${o[k]?'checked':''}>${l}</label>`).join('')}</div><button class="btn primary full" data-save-user="${u.id}">Guardar permisos</button></article>`}).join('')}</div>`}

function bindShell(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderShell()}));document.querySelector('#logout')?.addEventListener('click',()=>sb.auth.signOut());document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openCreate(b.dataset.open)));document.querySelectorAll('[data-menu-piggy]').forEach(b=>b.addEventListener('click',()=>openPiggyMenu(b.dataset.menuPiggy)));document.querySelectorAll('[data-menu-goal]').forEach(b=>b.addEventListener('click',()=>openGoalMenu(b.dataset.menuGoal)));document.querySelectorAll('[data-delete-folder]').forEach(b=>b.addEventListener('click',()=>deleteFolder(b.dataset.deleteFolder)));document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',()=>markRead(b.dataset.read)));document.querySelector('#read-all')?.addEventListener('click',markAllRead);document.querySelector('#create-user')?.addEventListener('click',openCreateUser);document.querySelectorAll('[data-save-user]').forEach(b=>b.addEventListener('click',()=>saveUser(b.dataset.saveUser)))}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-card">${html}</div></div>`);document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal'||e.target.closest('[data-close]'))closeModal()})}function closeModal(){document.querySelector('#modal')?.remove()}
function openCreate(type){const data={piggy:['Nueva hucha','Nombre de la hucha','Hucha'],folder:['Nueva carpeta','Nombre de la carpeta','Carpeta'],goal:['Nuevo objetivo','Nombre del objetivo','Objetivo']}[type];modal(`<form id="create-form"><div class="modal-head"><div><h3>${data[0]}</h3><p class="muted">${type==='piggy'?'Cuenta para meter y sacar dinero.':type==='folder'?'Solo organiza; no admite objetivos.':'Meta exclusiva de ahorro.'}</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>${data[1]}</label><input name="name" required maxlength="80"></div>${type==='piggy'?`<div class="field"><label>Emoji</label><input name="emoji" value="🏦" maxlength="4"></div>${state.permissions.can_create_shared?'<label class="check" style="margin-top:16px"><input name="shared" type="checkbox"> Hucha conjunta</label>':''}`:''}${type==='goal'?`<div class="field"><label>Importe objetivo (€)</label><input name="target" inputmode="decimal" required></div><div class="field"><label>Fecha límite</label><input name="date" type="date"></div>`:''}<div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#create-form').addEventListener('submit',e=>createEntity(e,type))}
async function createEntity(e,type){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),name=fd.get('name').trim();loading(b);let q;if(type==='piggy')q=sb.from('piggy_banks').insert({name,emoji:fd.get('emoji')||'🏦',is_shared:fd.get('shared')==='on'});if(type==='folder')q=sb.from('folders').insert({name});if(type==='goal'){const target=cents(fd.get('target'));if(target<=0){loading(b,false);return toast('Introduce un importe válido',true)}q=sb.from('goals').insert({name,target_cents:target,target_date:fd.get('date')||null})}const {error}=await q;if(error){loading(b,false);return err(error)}closeModal();await refreshAll();renderShell();toast(type==='goal'?'Objetivo guardado':'Guardado correctamente')}
function openPiggyMenu(id){const p=state.piggies.find(x=>x.id===id),s=piggyStats(id),canManage=p.owner_id===state.user.id||state.profile.role==='admin';modal(`<div class="modal-head"><div><h3>${esc(p.emoji)} ${esc(p.name)}</h3><p class="muted">Saldo ${money(s.balance)}</p></div><button class="close-btn" data-close>×</button></div><div class="list" style="margin-top:18px">${state.permissions.can_add_income?'<button class="btn" data-move="income">＋ Añadir fondos</button>':''}${state.permissions.can_add_expense?'<button class="btn" data-move="expense">− Registrar gasto</button>':''}${canManage&&state.permissions.can_manage_members?'<button class="btn" id="share-piggy">👥 Compartir con usuario</button>':''}<button class="btn" id="piggy-history">📄 Ver movimientos</button>${canManage?'<button class="btn danger" id="delete-piggy">Eliminar hucha</button>':''}</div>`);document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>openMovement(id,b.dataset.move)));document.querySelector('#share-piggy')?.addEventListener('click',()=>openShare(id));document.querySelector('#piggy-history').addEventListener('click',()=>{closeModal();state.tab='activity';renderShell()});document.querySelector('#delete-piggy')?.addEventListener('click',()=>deletePiggy(id))}
function openMovement(id,kind){const p=state.piggies.find(x=>x.id===id);closeModal();modal(`<form id="move-form"><div class="modal-head"><div><h3>${kind==='income'?'Añadir fondos':'Registrar gasto'}</h3><p class="muted">${esc(p.name)}</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Concepto</label><input name="concept" required maxlength="160"></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${today()}" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#move-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter,fd=new FormData(e.target),amount=cents(fd.get('amount'));if(amount<=0)return toast('Importe no válido',true);if(kind==='expense'&&amount>piggyStats(id).balance)return toast('La hucha no tiene saldo suficiente',true);loading(b);const {error}=await sb.from('piggy_transactions').insert({piggy_id:id,kind,amount_cents:amount,concept:fd.get('concept').trim(),occurred_on:fd.get('date')});if(error){loading(b,false);return err(error)}closeModal();await refreshLight();renderShell();toast(kind==='income'?'Fondos añadidos':'Gasto registrado')})}
function openShare(id){closeModal();modal(`<form id="share-form"><div class="modal-head"><div><h3>Compartir hucha</h3><p class="muted">El usuario debe haber iniciado sesión al menos una vez.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Email del usuario</label><input name="email" type="email" required></div><div class="field"><label>Rol</label><select name="role"><option value="editor">Puede operar</option><option value="viewer">Solo lectura</option><option value="owner">Copropietario</option></select></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Conceder acceso</button></div></form>`);document.querySelector('#share-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter,fd=new FormData(e.target);loading(b);const {error}=await sb.rpc('add_piggy_member_by_email',{p_piggy_id:id,p_email:fd.get('email').trim(),p_role:fd.get('role')});if(error){loading(b,false);return err(error)}closeModal();await refreshAll();renderShell();toast('Usuario añadido a la hucha')})}
function openGoalMenu(id){const g=state.goals.find(x=>x.id===id);modal(`<div class="modal-head"><div><h3>${esc(g.name)}</h3><p class="muted">Objetivo de ahorro</p></div><button class="close-btn" data-close>×</button></div><div class="list" style="margin-top:18px"><button class="btn" id="add-contribution">＋ Realizar aporte</button><button class="btn danger" id="delete-goal">Eliminar objetivo</button></div>`);document.querySelector('#add-contribution').addEventListener('click',()=>openContribution(id));document.querySelector('#delete-goal').addEventListener('click',()=>deleteGoal(id))}
function openContribution(id){closeModal();modal(`<form id="contribution-form"><div class="modal-head"><div><h3>Realizar aporte</h3><p class="muted">Este dinero solo cuenta para el objetivo.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Nota</label><input name="note" value="Aporte" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar aporte</button></div></form>`);document.querySelector('#contribution-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),amount=cents(fd.get('amount'));if(amount<=0)return toast('Importe no válido',true);const {error}=await sb.from('goal_contributions').insert({goal_id:id,amount_cents:amount,note:fd.get('note')});if(error)return err(error);closeModal();await refreshAll();renderShell();toast('Aporte guardado')})}
async function deletePiggy(id){if(!confirm('¿Eliminar esta hucha y todos sus movimientos?'))return;const {error}=await sb.from('piggy_banks').delete().eq('id',id);if(error)return err(error);closeModal();await refreshAll();renderShell()}
async function deleteGoal(id){if(!confirm('¿Eliminar este objetivo?'))return;const {error}=await sb.from('goals').delete().eq('id',id);if(error)return err(error);closeModal();await refreshAll();renderShell()}
async function deleteFolder(id){if(!confirm('¿Eliminar esta carpeta?'))return;const {error}=await sb.from('folders').delete().eq('id',id);if(error)return err(error);await refreshAll();renderShell()}
async function markRead(id){const {error}=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(error)return err(error);state.notifications.find(n=>n.id===id).read_at=new Date().toISOString();renderShell()}
async function markAllRead(){const {error}=await sb.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);if(error)return err(error);state.notifications.forEach(n=>n.read_at??=new Date().toISOString());renderShell()}
async function saveUser(id){const card=document.querySelector(`[data-user-card="${id}"]`),role=card.querySelector('[data-admin-role]').value,values={};card.querySelectorAll('[data-perm]').forEach(x=>values[x.dataset.perm]=x.checked);const {error}=await sb.rpc('admin_update_user',{p_user_id:id,p_role:role,p_active:values.active,p_can_create_piggy:values.can_create_piggy,p_can_create_shared:values.can_create_shared,p_can_add_income:values.can_add_income,p_can_add_expense:values.can_add_expense,p_can_manage_members:values.can_manage_members});if(error)return err(error);toast('Permisos actualizados');await refreshAll();renderShell()}
function openCreateUser(){modal(`<form id="create-user-form"><div class="modal-head"><div><h3>Registrar usuario</h3><p class="muted">Solo tú podrás crear cuentas. Entrega esta contraseña al usuario por un canal seguro.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Nombre</label><input name="display_name" required maxlength="80"></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Contraseña inicial</label><input name="password" type="password" minlength="8" required autocomplete="new-password"></div><div class="field"><label>Repetir contraseña</label><input name="confirm" type="password" minlength="8" required autocomplete="new-password"></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Crear usuario</button></div></form>`);document.querySelector('#create-user-form').addEventListener('submit',createUser)}
async function createUser(e){e.preventDefault();const btn=e.submitter,fd=new FormData(e.target),password=String(fd.get('password'));if(password!==fd.get('confirm'))return toast('Las contraseñas no coinciden',true);loading(btn);const {data,error}=await sb.functions.invoke('admin-create-user',{body:{email:String(fd.get('email')).trim().toLowerCase(),password,display_name:String(fd.get('display_name')).trim()}});loading(btn,false);if(error)return err(error);if(data?.error)return err(new Error(data.error));closeModal();await refreshAll();renderShell();toast('Usuario creado correctamente')}
