import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = window.A2C_CONFIG || {};
const configured = /^https:\/\/.+\.supabase\.co$/.test(cfg.SUPABASE_URL || '') && !String(cfg.SUPABASE_ANON_KEY || '').startsWith('TU_');
const sb = configured ? createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
const app = document.querySelector('#app');
const state = { session:null,user:null,profile:null,permissions:null,piggies:[],piggyTx:[],folders:[],goals:[],contributions:[],notifications:[],ledger:[],splits:[],sharedParts:[],invitations:[],directory:[],users:[],tab:'home',channel:null,folderFilter:null,filters:{q:'',from:'',to:'',amount:'',kind:'all'} };
let installPrompt = null;

const esc = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money = c => new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100);
const cents = v => { let s=String(v||'0').trim().replace(/\s|€/g,''); if(s.includes(',')) s=s.replace(/\./g,'').replace(',','.'); return Math.round(Number(s)*100); };
const today = () => new Date().toISOString().slice(0,10);
const dateFmt = v => v ? new Intl.DateTimeFormat('es-ES',{dateStyle:'medium'}).format(new Date(v+'T12:00:00')) : '';
const kindLabel = k => ({income:'Ingreso',expense:'Gasto',investment:'Inversión',transfer:'Traspaso'}[k] || k);
const kindIcon = k => ({income:'＋',expense:'−',investment:'↗',transfer:'⇄'}[k] || '•');
function toast(msg,bad=false){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.toggle('bad',bad);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function err(e){console.error(e);toast(e?.message||'Ha ocurrido un error',true)}
function loading(btn,on=true){if(!btn)return;btn.disabled=on;btn.dataset.label??=btn.textContent;btn.textContent=on?'Procesando…':btn.dataset.label}

if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
if(!configured) renderSetup(); else boot();

async function boot(){
  const {data}=await sb.auth.getSession(); state.session=data.session; state.user=data.session?.user||null;
  if(state.user) await enter(); else renderAuth();
  sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.user=session?.user||null;if(state.user&&!state.profile)await enter();if(!state.user){cleanupRealtime();Object.assign(state,{profile:null,permissions:null});renderAuth();}});
}
function renderSetup(){app.innerHTML='<section class="auth-shell"><div class="auth-card"><h1>A2C Finanzas</h1><p>Edita <strong>config.js</strong> con la URL y la clave pública de Supabase.</p></div></section>'}
function renderAuth(){app.innerHTML=`<section class="auth-shell"><form class="auth-card" id="auth-form"><div class="brand"><div class="brand-mark">A2C</div><div><h1>A2C Finanzas</h1><p>Acceso privado</p></div></div><h2>Iniciar sesión</h2><p class="muted">Usa la cuenta creada por el administrador.</p><div class="field"><label>Email</label><input id="auth-email" type="email" autocomplete="username" required></div><div class="field"><label>Contraseña</label><input id="auth-password" type="password" autocomplete="current-password" minlength="8" required></div><button class="btn primary full">Entrar</button></form></section>`;document.querySelector('#auth-form').addEventListener('submit',signIn)}
async function signIn(e){e.preventDefault();const b=e.submitter;loading(b);const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#auth-email').value.trim().toLowerCase(),password:document.querySelector('#auth-password').value});loading(b,false);if(error)err(new Error('Email o contraseña incorrectos'))}
async function enter(){try{const [{data:p,error:pe},{data:pm,error:pme}]=await Promise.all([sb.from('profiles').select('*').eq('id',state.user.id).single(),sb.from('user_permissions').select('*').eq('user_id',state.user.id).single()]);if(pe)throw pe;if(pme)throw pme;if(!p.active)throw new Error('Tu usuario está desactivado.');state.profile=p;state.permissions=pm;await refreshAll();subscribeRealtime();renderShell();}catch(e){err(e);renderAuth()}}

async function refreshAll(){
  const qs=[
    sb.from('piggy_banks').select('*,piggy_members(user_id,role,can_add_income,can_add_expense,profiles(display_name,email))').order('created_at',{ascending:false}),
    sb.from('piggy_transactions').select('*,profiles(display_name,email)').order('created_at',{ascending:false}),
    sb.from('folders').select('*').order('created_at',{ascending:false}),
    sb.from('goals').select('*,goal_members(user_id,role,profiles(display_name,email))').order('created_at',{ascending:false}),
    sb.from('goal_contributions').select('*').order('created_at',{ascending:false}),
    sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),
    sb.from('ledger_transactions').select('*,owner:profiles!ledger_transactions_owner_id_fkey(display_name,email),folder:folders!ledger_transactions_folder_id_fkey(name)').order('occurred_on',{ascending:false}),
    sb.from('expense_splits').select('*,profiles(display_name,email)').order('created_at',{ascending:true}),
    sb.from('profiles').select('id,email,display_name,active').eq('active',true).order('display_name')
  ];
  if(state.profile?.role==='admin')qs.push(sb.from('profiles').select('*,user_permissions(*)').order('created_at'));
  const rs=await Promise.all(qs); rs.forEach(r=>{if(r.error)throw r.error});
  [state.piggies,state.piggyTx,state.folders,state.goals,state.contributions,state.notifications,state.ledger,state.splits,state.directory]=rs.slice(0,9).map(r=>r.data||[]);
  state.users=rs[9]?.data||[];
}
async function refreshLight(){try{await refreshAll();renderShell()}catch(e){err(e)}}
function subscribeRealtime(){cleanupRealtime();state.channel=sb.channel('a2c-'+state.user.id).on('postgres_changes',{event:'*',schema:'public'},async()=>refreshLight()).subscribe()}
function cleanupRealtime(){if(state.channel&&sb)sb.removeChannel(state.channel);state.channel=null}

function mainBalance(){return state.ledger.reduce((s,t)=>s+(t.kind==='income'?Number(t.amount_cents):-Number(t.amount_cents)),0)}
function piggyStats(id){const list=state.piggyTx.filter(t=>t.piggy_id===id);const income=list.filter(t=>t.kind==='income').reduce((s,t)=>s+Number(t.amount_cents),0);const expense=list.filter(t=>t.kind==='expense').reduce((s,t)=>s+Number(t.amount_cents),0);return{income,expense,balance:income-expense,list}}
function totals(){return state.ledger.reduce((a,t)=>{if(t.kind==='income')a.income+=Number(t.amount_cents);if(t.kind==='expense')a.expense+=Number(t.amount_cents);if(t.kind==='investment')a.investment+=Number(t.amount_cents);return a},{income:0,expense:0,investment:0})}
function renderShell(){
  const unread=state.notifications.filter(n=>!n.read_at).length;
  app.innerHTML=`<div class="app-shell"><header class="topbar"><button class="brand-button" data-tab="home"><span class="brand-mark">A2C</span><span><strong>A2C Finanzas</strong><small>${esc(state.profile.display_name||state.profile.email)}</small></span></button><div class="top-actions"><button class="icon-btn" id="notifications-btn" aria-label="Avisos">🔔${unread?`<i class="badge">${unread}</i>`:''}</button><button class="icon-btn" id="account-menu" aria-label="Cuenta">👤</button></div></header><main id="view">${renderView()}</main><button class="quick-add" id="quick-add">＋<span>Movimiento</span></button><nav class="bottom-nav">${nav('home','⌂','Inicio')}${nav('piggies','🏦','Huchas')}${nav('folders','▣','Carpetas')}${nav('goals','◎','Objetivos')}${nav('activity','↕','Actividad')}</nav></div>`;
  bindShell();
}
function nav(tab,icon,label){return `<button class="nav-btn ${state.tab===tab?'active':''}" data-tab="${tab}"><span>${icon}</span>${label}</button>`}
function renderView(){return ({home:renderHome,piggies:renderPiggies,folders:renderFolders,goals:renderGoals,activity:renderActivity}[state.tab]||renderHome)()}

function renderHome(){const b=mainBalance(),t=totals(),saved=state.piggies.reduce((s,p)=>s+piggyStats(p.id).balance,0)+state.contributions.reduce((s,c)=>s+Number(c.amount_cents),0);const all=t.income+t.expense+saved+t.investment||1;const a=Math.round(saved/all*100),g=Math.round(t.expense/all*100),i=Math.max(0,100-a-g);return `<section class="home-grid"><article class="account-card"><div><span class="kicker">Cuenta principal</span><strong>${money(b)}</strong><small>Fondos disponibles para gastos, inversiones y traspasos</small></div><button class="btn light" id="transfer-btn">Pasar a hucha</button></article><div class="summary-grid"><article><span>Ingresos</span><strong class="positive">${money(t.income)}</strong></article><article><span>Gastos</span><strong class="negative">${money(t.expense)}</strong></article><article><span>Inversión</span><strong class="investment">${money(t.investment)}</strong></article></div><article class="chart-card"><div class="section-head compact"><div><h2>Distribución</h2><p>Ahorro, gastos e ingresos registrados</p></div></div><div class="pie-layout"><div class="pie" style="--a:${a}%;--g:${a+g}%"></div><div class="pie-legend"><span><i class="dot saving"></i>Ahorro <b>${money(saved)}</b></span><span><i class="dot expense"></i>Gastos <b>${money(t.expense)}</b></span><span><i class="dot income"></i>Ingresos <b>${money(t.income)}</b></span></div></div></article><div class="section-head compact"><div><h2>Movimientos recientes</h2><p>Cuenta principal</p></div><button class="link-btn" data-tab="activity">Ver todos</button></div><div class="transaction-list">${state.ledger.slice(0,6).map(txCard).join('')||'<div class="empty">Todavía no hay movimientos.</div>'}</div></section>`}
function renderPiggies(){return `<div class="section-head"><div><h2>Huchas</h2><p>Personales y conjuntas</p></div>${state.permissions.can_create_piggy?'<button class="btn primary" data-open="piggy">Nueva</button>':''}</div><div class="card-grid">${state.piggies.map(p=>{const s=piggyStats(p.id);return `<article class="entity-card"><button class="entity-menu" data-piggy-menu="${p.id}">•••</button><div class="entity-top"><div class="emoji">${esc(p.emoji||'🏦')}</div><div><div class="entity-name">${esc(p.name)}</div><div class="entity-type">${p.is_shared?'Conjunta · '+(p.piggy_members?.length||0)+' miembros':'Personal'}</div></div></div><div class="balance-box"><span>Saldo</span><strong>${money(s.balance)}</strong></div><div class="minis"><div class="mini"><span>Entradas</span><strong class="positive">${money(s.income)}</strong></div><div class="mini"><span>Salidas</span><strong class="negative">${money(s.expense)}</strong></div></div></article>`}).join('')||'<div class="empty">No tienes huchas.</div>'}</div>`}
function folderStats(id){const l=state.ledger.filter(t=>t.folder_id===id);return l.reduce((a,t)=>{a[t.kind]=(a[t.kind]||0)+Number(t.amount_cents);return a},{income:0,expense:0,investment:0})}
function renderFolders(){return `<div class="section-head"><div><h2>Carpetas</h2><p>Ingresos, gastos e inversiones organizados</p></div><button class="btn primary" data-open="folder">Nueva</button></div><div class="card-grid">${state.folders.map(f=>{const s=folderStats(f.id);return `<article class="entity-card"><button class="entity-menu" data-folder-menu="${f.id}">•••</button><div class="entity-top"><div class="emoji">${esc(f.emoji||'📁')}</div><div><div class="entity-name">${esc(f.name)}</div><div class="entity-type">Carpeta</div></div></div><div class="minis three"><div class="mini"><span>Ingresos</span><strong class="positive">${money(s.income)}</strong></div><div class="mini"><span>Gastos</span><strong class="negative">${money(s.expense)}</strong></div><div class="mini"><span>Inversión</span><strong class="investment">${money(s.investment)}</strong></div></div></article>`}).join('')||'<div class="empty">No hay carpetas.</div>'}</div>`}
function goalSaved(id){return state.contributions.filter(c=>c.goal_id===id).reduce((s,c)=>s+Number(c.amount_cents),0)}
function renderGoals(){return `<div class="section-head"><div><h2>Objetivos</h2><p>Metas personales y compartidas</p></div><button class="btn primary" data-open="goal">Nuevo</button></div><div class="card-grid">${state.goals.map(g=>{const saved=goalSaved(g.id),pct=Math.min(100,Math.round(saved/Number(g.target_cents||1)*100));return `<article class="entity-card"><button class="entity-menu" data-goal-menu="${g.id}">•••</button><div class="entity-top"><div class="emoji">${esc(g.emoji||'🎯')}</div><div><div class="entity-name">${esc(g.name)}</div><div class="entity-type">${g.is_shared?'Compartido':'Personal'} · ${pct}%</div></div></div><div class="balance-box"><span>Ahorrado</span><strong>${money(saved)}</strong><div class="progress"><i style="width:${pct}%"></i></div></div><div class="minis"><div class="mini"><span>Meta</span><strong>${money(g.target_cents)}</strong></div><div class="mini"><span>Falta</span><strong>${money(Math.max(0,g.target_cents-saved))}</strong></div></div></article>`}).join('')||'<div class="empty">No hay objetivos.</div>'}</div>`}
function filteredLedger(){const f=state.filters,amount=cents(f.amount);return state.ledger.filter(t=>(!f.q||String(t.concept).toLowerCase().includes(f.q.toLowerCase()))&&(!f.from||t.occurred_on>=f.from)&&(!f.to||t.occurred_on<=f.to)&&(!f.amount||Number(t.amount_cents)===amount)&&(f.kind==='all'||t.kind===f.kind))}
function renderActivity(){const rows=filteredLedger();return `<div class="section-head"><div><h2>Actividad y analíticas</h2><p>Busca y filtra todas tus transacciones</p></div></div><form class="filters" id="filters-form"><div class="field"><label>Concepto</label><input name="q" value="${esc(state.filters.q)}" placeholder="Buscar..."></div><div class="filter-grid"><div class="field"><label>Desde</label><input type="date" name="from" value="${esc(state.filters.from)}"></div><div class="field"><label>Hasta</label><input type="date" name="to" value="${esc(state.filters.to)}"></div></div><div class="filter-grid"><div class="field"><label>Importe exacto (€)</label><input name="amount" inputmode="decimal" value="${esc(state.filters.amount)}"></div><div class="field"><label>Tipo</label><select name="kind"><option value="all">Todos</option><option value="income" ${state.filters.kind==='income'?'selected':''}>Ingreso</option><option value="expense" ${state.filters.kind==='expense'?'selected':''}>Gasto</option><option value="investment" ${state.filters.kind==='investment'?'selected':''}>Inversión</option></select></div></div><div class="form-actions"><button type="button" class="btn" id="clear-filters">Limpiar</button><button class="btn primary">Buscar</button></div></form><div class="results-count">${rows.length} movimientos</div><div class="transaction-list">${rows.map(txCard).join('')||'<div class="empty">No hay resultados.</div>'}</div>`}
function txCard(t){const scope=t.folder?.name||'Cuenta principal';return `<article class="tx-card"><div class="tx-icon ${t.kind}">${kindIcon(t.kind)}</div><div class="tx-main"><strong>${esc(t.concept)}</strong><small>${esc(scope)} · ${dateFmt(t.occurred_on)}</small></div><div class="tx-end"><b class="${t.kind}">${t.kind==='income'?'+':'−'}${money(t.amount_cents)}</b><button class="mini-btn" data-edit-ledger="${t.id}">Editar</button></div></article>`}

function bindShell(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderShell()}));
  document.querySelector('#quick-add')?.addEventListener('click',()=>openMovement());
  document.querySelector('#transfer-btn')?.addEventListener('click',openTransfer);
  document.querySelector('#notifications-btn')?.addEventListener('click',openNotifications);
  document.querySelector('#account-menu')?.addEventListener('click',openAccountMenu);
  document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openCreate(b.dataset.open)));
  document.querySelectorAll('[data-piggy-menu]').forEach(b=>b.addEventListener('click',()=>openPiggyMenu(b.dataset.piggyMenu)));
  document.querySelectorAll('[data-folder-menu]').forEach(b=>b.addEventListener('click',()=>openFolderMenu(b.dataset.folderMenu)));
  document.querySelectorAll('[data-goal-menu]').forEach(b=>b.addEventListener('click',()=>openGoalMenu(b.dataset.goalMenu)));
  document.querySelectorAll('[data-edit-ledger]').forEach(b=>b.addEventListener('click',()=>openEditLedger(b.dataset.editLedger)));
  document.querySelector('#filters-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);state.filters={q:String(fd.get('q')||''),from:String(fd.get('from')||''),to:String(fd.get('to')||''),amount:String(fd.get('amount')||''),kind:String(fd.get('kind')||'all')};renderShell()});
  document.querySelector('#clear-filters')?.addEventListener('click',()=>{state.filters={q:'',from:'',to:'',amount:'',kind:'all'};renderShell()});
}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-card">${html}</div></div>`);document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal'||e.target.closest('[data-close]'))closeModal()})}
function closeModal(){document.querySelector('#modal')?.remove()}

function openMovement(prefill={}){const folderOptions=state.folders.map(f=>`<option value="${f.id}" ${prefill.folder_id===f.id?'selected':''}>${esc(f.name)}</option>`).join('');modal(`<form id="movement-form"><div class="modal-head"><div><h3>${prefill.id?'Editar':'Nuevo'} movimiento</h3><p class="muted">Se aplica a la cuenta principal.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Tipo</label><select name="kind"><option value="expense" ${prefill.kind==='expense'?'selected':''}>Gasto</option><option value="income" ${prefill.kind==='income'?'selected':''}>Ingreso</option><option value="investment" ${prefill.kind==='investment'?'selected':''}>Inversión</option></select></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required value="${prefill.amount_cents?Number(prefill.amount_cents)/100:''}"></div><div class="field"><label>Concepto</label><input name="concept" required maxlength="160" value="${esc(prefill.concept||'')}"></div><div class="field"><label>Fecha</label><input name="date" type="date" required value="${prefill.occurred_on||today()}"></div><div class="field"><label>Carpeta</label><select name="folder"><option value="">Sin carpeta</option>${folderOptions}</select></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#movement-form').addEventListener('submit',e=>saveMovement(e,prefill.id))}
async function saveMovement(e,id){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),amount=cents(fd.get('amount'));if(amount<=0)return toast('Importe no válido',true);const payload={kind:fd.get('kind'),amount_cents:amount,concept:String(fd.get('concept')).trim(),occurred_on:fd.get('date'),folder_id:fd.get('folder')||null};loading(b);const q=id?sb.from('ledger_transactions').update(payload).eq('id',id):sb.from('ledger_transactions').insert(payload);const {error}=await q;loading(b,false);if(error)return err(error);closeModal();await refreshAll();renderShell();toast(id?'Movimiento actualizado':'Movimiento guardado')}
function openEditLedger(id){const t=state.ledger.find(x=>x.id===id);if(t?.kind==='transfer')return toast('Los traspasos se corrigen desde la hucha o se eliminan y vuelven a crear.',true);openMovement(t)}

function openTransfer(){if(!state.piggies.length)return toast('Primero crea una hucha.',true);modal(`<form id="transfer-form"><div class="modal-head"><div><h3>Pasar dinero a una hucha</h3><p class="muted">Se descontará de la cuenta principal.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Hucha</label><select name="piggy">${state.piggies.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Concepto</label><input name="concept" value="Traspaso a hucha" required></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${today()}" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Traspasar</button></div></form>`);document.querySelector('#transfer-form').addEventListener('submit',saveTransfer)}
async function saveTransfer(e){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),amount=cents(fd.get('amount'));if(amount<=0)return toast('Importe no válido',true);if(amount>mainBalance())return toast('No hay saldo suficiente en la cuenta principal.',true);loading(b);const {error}=await sb.rpc('transfer_main_to_piggy',{p_piggy_id:fd.get('piggy'),p_amount_cents:amount,p_concept:String(fd.get('concept')).trim(),p_occurred_on:fd.get('date')});loading(b,false);if(error)return err(error);closeModal();await refreshAll();renderShell();toast('Dinero traspasado')}

function openCreate(type){const d={piggy:['Nueva hucha','Hucha'],folder:['Nueva carpeta','Carpeta'],goal:['Nuevo objetivo','Objetivo']}[type];modal(`<form id="create-form"><div class="modal-head"><div><h3>${d[0]}</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Nombre</label><input name="name" required maxlength="80"></div>${type==='piggy'?'<div class="field"><label>Emoji</label><input name="emoji" value="🏦"></div><label class="check"><input name="shared" type="checkbox"> Hucha conjunta</label>':''}${type==='goal'?'<div class="field"><label>Importe objetivo (€)</label><input name="target" inputmode="decimal" required></div><div class="field"><label>Fecha límite</label><input name="date" type="date"></div><label class="check"><input name="shared" type="checkbox"> Objetivo compartido</label>':''}<div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#create-form').addEventListener('submit',e=>createEntity(e,type))}
async function createEntity(e,type){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),name=String(fd.get('name')).trim();let q;if(type==='piggy')q=sb.from('piggy_banks').insert({name,emoji:fd.get('emoji')||'🏦',is_shared:fd.get('shared')==='on'});if(type==='folder')q=sb.from('folders').insert({name});if(type==='goal')q=sb.from('goals').insert({name,target_cents:cents(fd.get('target')),target_date:fd.get('date')||null,is_shared:fd.get('shared')==='on'});loading(b);const {error}=await q;loading(b,false);if(error)return err(error);closeModal();await refreshAll();renderShell()}

function openPiggyMenu(id){const p=state.piggies.find(x=>x.id===id),s=piggyStats(id);modal(`<div class="modal-head"><div><h3>${esc(p.name)}</h3><p class="muted">Saldo ${money(s.balance)}</p></div><button class="close-btn" data-close>×</button></div><div class="menu-list"><button class="btn" id="transfer-here">Pasar desde cuenta principal</button><button class="btn" id="piggy-income">Añadir ingreso directo</button><button class="btn" id="piggy-expense">Añadir gasto</button>${p.is_shared?'<button class="btn" id="share-piggy">Gestionar miembros</button>':''}<button class="btn" id="piggy-history">Ver y editar movimientos</button></div>`);document.querySelector('#transfer-here').onclick=()=>{closeModal();openTransfer()};document.querySelector('#piggy-income').onclick=()=>openPiggyTx(id,'income');document.querySelector('#piggy-expense').onclick=()=>openPiggyTx(id,'expense');document.querySelector('#piggy-history').onclick=()=>openPiggyHistory(id);document.querySelector('#share-piggy')?.addEventListener('click',()=>openSharePiggy(id))}
function openPiggyTx(piggyId,kind,prefill={}){closeModal();modal(`<form id="piggy-tx-form"><div class="modal-head"><div><h3>${prefill.id?'Editar':'Nuevo'} ${kind==='income'?'ingreso':'gasto'} en hucha</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required value="${prefill.amount_cents?Number(prefill.amount_cents)/100:''}"></div><div class="field"><label>Concepto</label><input name="concept" required value="${esc(prefill.concept||'')}"></div><div class="field"><label>Fecha</label><input name="date" type="date" required value="${prefill.occurred_on||today()}"></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#piggy-tx-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),payload={piggy_id:piggyId,kind,amount_cents:cents(fd.get('amount')),concept:String(fd.get('concept')).trim(),occurred_on:fd.get('date')};const {error}=prefill.id?await sb.from('piggy_transactions').update(payload).eq('id',prefill.id):await sb.from('piggy_transactions').insert(payload);if(error)return err(error);closeModal();await refreshAll();renderShell()})}
function openPiggyHistory(id){closeModal();const rows=state.piggyTx.filter(t=>t.piggy_id===id);modal(`<div class="modal-head"><div><h3>Movimientos de la hucha</h3></div><button class="close-btn" data-close>×</button></div><div class="transaction-list modal-list">${rows.map(t=>`<article class="tx-card"><div class="tx-icon ${t.kind}">${kindIcon(t.kind)}</div><div class="tx-main"><strong>${esc(t.concept)}</strong><small>${dateFmt(t.occurred_on)}</small></div><div class="tx-end"><b>${money(t.amount_cents)}</b><button class="mini-btn" data-edit-piggy="${t.id}">Editar</button></div></article>`).join('')||'<div class="empty">Sin movimientos</div>'}</div>`);document.querySelectorAll('[data-edit-piggy]').forEach(b=>b.addEventListener('click',()=>{const t=state.piggyTx.find(x=>x.id===b.dataset.editPiggy);openPiggyTx(id,t.kind,t)}))}
function openSharePiggy(id){closeModal();modal(`<form id="share-form"><div class="modal-head"><div><h3>Añadir miembro</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Rol</label><select name="role"><option value="editor">Puede operar</option><option value="viewer">Solo lectura</option><option value="owner">Copropietario</option></select></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Añadir</button></div></form>`);document.querySelector('#share-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{error}=await sb.rpc('add_piggy_member_by_email',{p_piggy_id:id,p_email:String(fd.get('email')).trim(),p_role:fd.get('role')});if(error)return err(error);closeModal();await refreshAll();renderShell()})}

function openFolderMenu(id){const f=state.folders.find(x=>x.id===id);modal(`<div class="modal-head"><div><h3>${esc(f.name)}</h3></div><button class="close-btn" data-close>×</button></div><div class="menu-list"><button class="btn" id="folder-add">Añadir movimiento</button><button class="btn" id="folder-view">Ver movimientos</button></div>`);document.querySelector('#folder-add').onclick=()=>{closeModal();openMovement({folder_id:id})};document.querySelector('#folder-view').onclick=()=>{closeModal();state.filters={q:'',from:'',to:'',amount:'',kind:'all'};state.tab='activity';renderShell();toast('Usa el buscador para localizar los movimientos de esta carpeta.')};}
function openGoalMenu(id){const g=state.goals.find(x=>x.id===id);modal(`<div class="modal-head"><div><h3>${esc(g.name)}</h3></div><button class="close-btn" data-close>×</button></div><div class="menu-list"><button class="btn" id="goal-add">Añadir aporte</button>${g.is_shared?'<button class="btn" id="goal-share">Compartir objetivo</button>':''}</div>`);document.querySelector('#goal-add').onclick=()=>openContribution(id);document.querySelector('#goal-share')?.addEventListener('click',()=>openShareGoal(id))}
function openContribution(id){closeModal();modal(`<form id="contrib-form"><div class="modal-head"><div><h3>Nuevo aporte</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Nota</label><input name="note" value="Aporte" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#contrib-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{error}=await sb.from('goal_contributions').insert({goal_id:id,amount_cents:cents(fd.get('amount')),note:fd.get('note')});if(error)return err(error);closeModal();await refreshAll();renderShell()})}
function openShareGoal(id){closeModal();modal(`<form id="share-goal-form"><div class="modal-head"><div><h3>Compartir objetivo</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Rol</label><select name="role"><option value="editor">Puede aportar</option><option value="viewer">Solo lectura</option><option value="owner">Copropietario</option></select></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Compartir</button></div></form>`);document.querySelector('#share-goal-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{error}=await sb.rpc('add_goal_member_by_email',{p_goal_id:id,p_email:String(fd.get('email')).trim(),p_role:fd.get('role')});if(error)return err(error);closeModal();await refreshAll();renderShell()})}

function openNotifications(){modal(`<div class="modal-head"><div><h3>Avisos</h3><p class="muted">${state.notifications.filter(n=>!n.read_at).length} sin leer</p></div><button class="close-btn" data-close>×</button></div><div class="notification-actions"><button class="btn" id="mark-all">Marcar todos como leídos</button></div><div class="list modal-list">${state.notifications.map(n=>`<div class="list-row ${n.read_at?'':'unread'}"><div><div class="list-title">${esc(n.title)}</div><div class="list-meta">${esc(n.body)} · ${dateFmt(n.created_at?.slice(0,10))}</div></div><button class="mini-btn" data-read="${n.id}">${n.read_at?'Leído':'Marcar'}</button></div>`).join('')||'<div class="empty">No hay avisos.</div>'}</div>`);document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',async()=>{await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',b.dataset.read);closeModal();await refreshAll();renderShell();openNotifications()}));document.querySelector('#mark-all')?.addEventListener('click',async()=>{await sb.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);closeModal();await refreshAll();renderShell()})}
function openAccountMenu(){modal(`<div class="modal-head"><div><h3>${esc(state.profile.display_name||state.profile.email)}</h3><p class="muted">${esc(state.profile.email)}</p></div><button class="close-btn" data-close>×</button></div><div class="menu-list">${state.profile.role==='admin'?'<button class="btn" id="admin-panel">Administración</button>':''}${installPrompt?'<button class="btn" id="install-app">Instalar aplicación</button>':''}<button class="btn danger" id="logout">Cerrar sesión</button></div>`);document.querySelector('#logout').onclick=()=>sb.auth.signOut();document.querySelector('#install-app')?.addEventListener('click',async()=>{installPrompt.prompt();await installPrompt.userChoice;installPrompt=null});document.querySelector('#admin-panel')?.addEventListener('click',openAdmin)}
function openAdmin(){closeModal();modal(`<div class="modal-head"><div><h3>Administración</h3><p class="muted">Usuarios y permisos</p></div><button class="close-btn" data-close>×</button></div><button class="btn primary full" id="create-user">Nuevo usuario</button><div class="admin-table modal-list">${state.users.map(u=>`<article class="user-card"><div class="list-title">${esc(u.display_name||u.email)}</div><div class="list-meta">${esc(u.email)} · ${esc(u.role)}</div></article>`).join('')}</div>`);document.querySelector('#create-user').onclick=openCreateUser}
function openCreateUser(){closeModal();modal(`<form id="create-user-form"><div class="modal-head"><div><h3>Nuevo usuario</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Nombre</label><input name="display_name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="8" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Crear</button></div></form>`);document.querySelector('#create-user-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{data,error}=await sb.functions.invoke('admin-create-user',{body:{email:String(fd.get('email')).trim().toLowerCase(),password:String(fd.get('password')),display_name:String(fd.get('display_name')).trim()}});if(error||data?.error)return err(error||new Error(data.error));closeModal();await refreshAll();renderShell();toast('Usuario creado')})}


/* ===== A2C V3: seguridad, invitaciones, gastos compartidos y administración ===== */
async function refreshAll(){
  const qs=[
    sb.from('piggy_banks').select('*,piggy_members(user_id,role,can_add_income,can_add_expense,profiles(display_name,email))').order('created_at',{ascending:false}),
    sb.from('piggy_transactions').select('*,profiles(display_name,email)').order('created_at',{ascending:false}),
    sb.from('folders').select('*').order('created_at',{ascending:false}),
    sb.from('goals').select('*,goal_members(user_id,role,profiles(display_name,email))').order('created_at',{ascending:false}),
    sb.from('goal_contributions').select('*').order('created_at',{ascending:false}),
    sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),
    sb.from('ledger_transactions').select('*,owner:profiles!ledger_transactions_owner_id_fkey(display_name,email),folder:folders!ledger_transactions_folder_id_fkey(name)').order('occurred_on',{ascending:false}),
    sb.from('expense_splits').select('*,profiles(display_name,email)').order('created_at',{ascending:true}),
    sb.from('shared_expense_parts').select('*,profiles(display_name,email)').order('created_at',{ascending:true}),
    sb.from('shared_invitations').select('*').eq('invitee_id',state.user.id).eq('status','pending').order('created_at',{ascending:false}),
    sb.from('profiles').select('id,email,display_name,active').eq('active',true).order('display_name')
  ];
  if(state.profile?.role==='admin')qs.push(sb.from('profiles').select('*,user_permissions(*)').order('created_at'));
  const rs=await Promise.all(qs);rs.forEach(r=>{if(r.error)throw r.error});
  [state.piggies,state.piggyTx,state.folders,state.goals,state.contributions,state.notifications,state.ledger,state.splits,state.sharedParts,state.invitations,state.directory]=rs.slice(0,11).map(r=>r.data||[]);
  state.users=rs[11]?.data||[];
}

function filteredLedger(){const f=state.filters,amount=cents(f.amount);return state.ledger.filter(t=>(!state.folderFilter||t.folder_id===state.folderFilter)&&(!f.q||String(t.concept).toLowerCase().includes(f.q.toLowerCase()))&&(!f.from||t.occurred_on>=f.from)&&(!f.to||t.occurred_on<=f.to)&&(!f.amount||Number(t.amount_cents)===amount)&&(f.kind==='all'||t.kind===f.kind))}
function txCard(t){const scope=t.folder?.name||'Cuenta principal';return `<article class="tx-card"><div class="tx-icon ${t.kind}">${kindIcon(t.kind)}</div><div class="tx-main"><strong>${esc(t.concept)}</strong><small>${esc(scope)} · ${dateFmt(t.occurred_on)}</small></div><div class="tx-end"><b class="${t.kind}">${t.kind==='income'?'+':'−'}${money(t.amount_cents)}</b><div class="tx-buttons"><button class="mini-btn" data-edit-ledger="${t.id}">Editar</button><button class="mini-btn danger" data-delete-ledger="${t.id}">Borrar</button></div></div></article>`}
function bindShell(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;if(state.tab!=='activity')state.folderFilter=null;renderShell()}));
 document.querySelector('#quick-add')?.addEventListener('click',()=>openMovement());document.querySelector('#transfer-btn')?.addEventListener('click',openTransfer);document.querySelector('#notifications-btn')?.addEventListener('click',openNotifications);document.querySelector('#account-menu')?.addEventListener('click',openAccountMenu);
 document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openCreate(b.dataset.open)));document.querySelectorAll('[data-piggy-menu]').forEach(b=>b.addEventListener('click',()=>openPiggyMenu(b.dataset.piggyMenu)));document.querySelectorAll('[data-folder-menu]').forEach(b=>b.addEventListener('click',()=>openFolderMenu(b.dataset.folderMenu)));document.querySelectorAll('[data-goal-menu]').forEach(b=>b.addEventListener('click',()=>openGoalMenu(b.dataset.goalMenu)));
 document.querySelectorAll('[data-edit-ledger]').forEach(b=>b.addEventListener('click',()=>openEditLedger(b.dataset.editLedger)));document.querySelectorAll('[data-delete-ledger]').forEach(b=>b.addEventListener('click',()=>deleteLedger(b.dataset.deleteLedger)));
 document.querySelector('#filters-form')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);state.filters={q:String(fd.get('q')||''),from:String(fd.get('from')||''),to:String(fd.get('to')||''),amount:String(fd.get('amount')||''),kind:String(fd.get('kind')||'all')};renderShell()});document.querySelector('#clear-filters')?.addEventListener('click',()=>{state.filters={q:'',from:'',to:'',amount:'',kind:'all'};state.folderFilter=null;renderShell()});
}
async function deleteLedger(id){if(!confirm('¿Eliminar este movimiento?'))return;const {error}=await sb.from('ledger_transactions').delete().eq('id',id);if(error)return err(error);await refreshAll();renderShell();toast('Movimiento eliminado')}

function splitSection(piggyId=''){const p=state.piggies.find(x=>x.id===piggyId);const members=(p?.piggy_members||[]).filter(m=>m.user_id!==state.user.id);return `<div id="expense-extra" class="expense-extra"><div class="field"><label>Justificante (opcional)</label><input name="receipt" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment"></div><label class="check"><input name="split_enabled" type="checkbox" id="split-enabled"> Dividir este gasto</label><div id="split-controls" class="hidden"><div class="field"><label>Reparto</label><select name="split_mode"><option value="equal">Partes iguales</option><option value="custom">Importes concretos</option></select></div><div class="split-people">${members.map(m=>`<label class="split-person"><input type="checkbox" data-split-user="${m.user_id}"><span>${esc(m.profiles?.display_name||m.profiles?.email||'Usuario')}</span><input type="number" step="0.01" min="0" data-split-amount="${m.user_id}" placeholder="0,00" disabled></label>`).join('')||'<p class="muted">Selecciona una hucha conjunta con miembros para dividir el gasto.</p>'}</div></div></div>`}
function openMovement(prefill={}){const folderOptions=state.folders.map(f=>`<option value="${f.id}" ${prefill.folder_id===f.id?'selected':''}>${esc(f.name)}</option>`).join('');const piggyOptions=state.piggies.map(p=>`<option value="${p.id}">${esc(p.name)}${p.is_shared?' · conjunta':''}</option>`).join('');modal(`<form id="movement-form"><div class="modal-head"><div><h3>${prefill.id?'Editar':'Nuevo'} movimiento</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Tipo</label><select name="kind" id="movement-kind"><option value="expense" ${prefill.kind==='expense'?'selected':''}>Gasto</option><option value="income" ${prefill.kind==='income'?'selected':''}>Ingreso</option><option value="investment" ${prefill.kind==='investment'?'selected':''}>Inversión</option></select></div>${prefill.id?'':`<div class="field"><label>Origen / destino</label><select name="source" id="movement-source"><option value="main">Cuenta principal</option>${piggyOptions?'<optgroup label="Huchas">'+piggyOptions+'</optgroup>':''}</select></div>`}<div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required value="${prefill.amount_cents?Number(prefill.amount_cents)/100:''}"></div><div class="field"><label>Concepto</label><input name="concept" required maxlength="160" value="${esc(prefill.concept||'')}"></div><div class="field"><label>Fecha</label><input name="date" type="date" required value="${prefill.occurred_on||today()}"></div><div class="field" id="folder-field"><label>Carpeta</label><select name="folder"><option value="">Sin carpeta</option>${folderOptions}</select></div><div id="dynamic-extra"></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);const form=document.querySelector('#movement-form'),update=()=>{const kind=form.elements.kind.value,source=form.elements.source?.value||'main';document.querySelector('#folder-field')?.classList.toggle('hidden',source!=='main');document.querySelector('#dynamic-extra').innerHTML=kind==='expense'&&!prefill.id?splitSection(source==='main'?'':source):'';document.querySelector('#split-enabled')?.addEventListener('change',e=>document.querySelector('#split-controls').classList.toggle('hidden',!e.target.checked));document.querySelectorAll('[data-split-user]').forEach(c=>c.addEventListener('change',()=>document.querySelector(`[data-split-amount="${c.dataset.splitUser}"]`).disabled=!c.checked))};form.elements.kind.addEventListener('change',update);form.elements.source?.addEventListener('change',update);update();form.addEventListener('submit',e=>saveMovementV3(e,prefill.id))}
async function uploadReceipt(file){if(!file?.size)return null;if(file.size>10485760)throw new Error('La foto supera 10 MB');const path=`${state.user.id}/${crypto.randomUUID()}-${String(file.name).replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sb.storage.from('receipts').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
async function saveMovementV3(e,id){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),amount=cents(fd.get('amount'));if(amount<=0)return toast('Importe no válido',true);loading(b);try{if(id){const {error}=await sb.from('ledger_transactions').update({kind:fd.get('kind'),amount_cents:amount,concept:String(fd.get('concept')).trim(),occurred_on:fd.get('date'),folder_id:fd.get('folder')||null}).eq('id',id);if(error)throw error}else{const source=fd.get('source')||'main',receipt=await uploadReceipt(fd.get('receipt'));let tx;if(source==='main'){const {data,error}=await sb.from('ledger_transactions').insert({kind:fd.get('kind'),amount_cents:amount,concept:String(fd.get('concept')).trim(),occurred_on:fd.get('date'),folder_id:fd.get('folder')||null,receipt_path:receipt}).select().single();if(error)throw error;tx=data}else{const {data,error}=await sb.from('piggy_transactions').insert({piggy_id:source,kind:fd.get('kind'),amount_cents:amount,concept:String(fd.get('concept')).trim(),occurred_on:fd.get('date'),receipt_path:receipt}).select().single();if(error)throw error;tx=data}if(fd.get('kind')==='expense'&&fd.get('split_enabled')==='on'){const ids=[...e.target.querySelectorAll('[data-split-user]:checked')].map(x=>x.dataset.splitUser);if(!ids.length)throw new Error('Selecciona al menos una persona');const mode=fd.get('split_mode'),base=Math.floor(amount/ids.length),rem=amount-base*ids.length;const parts=ids.map((uid,i)=>({user_id:uid,amount_cents:mode==='equal'?base+(i===0?rem:0):cents(e.target.querySelector(`[data-split-amount="${uid}"]`).value)}));if(parts.some(x=>x.amount_cents<=0)||parts.reduce((s,x)=>s+x.amount_cents,0)>amount)throw new Error('Revisa los importes del reparto');const {error}=await sb.rpc('create_shared_expense_parts',{p_source_type:source==='main'?'ledger':'piggy',p_source_id:tx.id,p_parts:parts});if(error)throw error}}closeModal();await refreshAll();renderShell();toast(id?'Movimiento actualizado':'Movimiento guardado')}catch(ex){err(ex)}finally{loading(b,false)}}

function openCreate(type){const d={piggy:['Nueva hucha','Hucha'],folder:['Nueva carpeta','Carpeta'],goal:['Nuevo objetivo','Objetivo']}[type];modal(`<form id="create-form"><div class="modal-head"><div><h3>${d[0]}</h3></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Nombre</label><input name="name" required maxlength="80"></div>${type==='piggy'?'<div class="field"><label>Emoji</label><input name="emoji" value="🏦"></div><label class="check"><input name="shared" type="checkbox" id="create-shared"> Hucha conjunta</label><div class="field hidden" id="invite-field"><label>Email del usuario a invitar</label><input name="invite_email" type="email"></div>':''}${type==='goal'?'<div class="field"><label>Importe objetivo (€)</label><input name="target" inputmode="decimal" required></div><div class="field"><label>Fecha límite</label><input name="date" type="date"></div><label class="check"><input name="shared" type="checkbox" id="create-shared"> Objetivo compartido</label><div class="field hidden" id="invite-field"><label>Email del usuario a invitar</label><input name="invite_email" type="email"></div>':''}<div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.querySelector('#create-shared')?.addEventListener('change',e=>{document.querySelector('#invite-field').classList.toggle('hidden',!e.target.checked);document.querySelector('[name=invite_email]').required=e.target.checked});document.querySelector('#create-form').addEventListener('submit',e=>createEntityV3(e,type))}
async function createEntityV3(e,type){e.preventDefault();const b=e.submitter,fd=new FormData(e.target),name=String(fd.get('name')).trim(),shared=fd.get('shared')==='on';loading(b);try{let table,payload;if(type==='piggy'){table='piggy_banks';payload={name,emoji:fd.get('emoji')||'🏦',is_shared:shared}}if(type==='folder'){table='folders';payload={name}}if(type==='goal'){table='goals';payload={name,target_cents:cents(fd.get('target')),target_date:fd.get('date')||null,is_shared:shared}}const {data,error}=await sb.from(table).insert(payload).select().single();if(error)throw error;if(shared){const {error:ie}=await sb.rpc('invite_shared_resource',{p_resource_type:type,p_resource_id:data.id,p_email:String(fd.get('invite_email')).trim().toLowerCase()});if(ie)throw ie}closeModal();await refreshAll();renderShell();toast(shared?'Creado e invitación enviada':'Creado correctamente')}catch(ex){err(ex)}finally{loading(b,false)}}

function canDeletePiggyTx(t,p){return state.profile.role==='admin'||t.user_id===state.user.id}
function openPiggyMenu(id){const p=state.piggies.find(x=>x.id===id),s=piggyStats(id),canDelete=state.profile.role==='admin'||p.owner_id===state.user.id;modal(`<div class="modal-head"><div><h3>${esc(p.name)}</h3><p class="muted">Saldo ${money(s.balance)}</p></div><button class="close-btn" data-close>×</button></div><div class="menu-list"><button class="btn" id="transfer-here">Pasar desde cuenta principal</button><button class="btn" id="piggy-income">Añadir ingreso directo</button><button class="btn" id="piggy-expense">Añadir gasto</button>${p.is_shared?'<button class="btn" id="share-piggy">Invitar miembro</button>':''}<button class="btn" id="piggy-history">Ver movimientos</button>${canDelete?'<button class="btn danger" id="delete-piggy">Eliminar hucha</button>':''}</div>`);document.querySelector('#transfer-here').onclick=()=>{closeModal();openTransfer()};document.querySelector('#piggy-income').onclick=()=>openPiggyTx(id,'income');document.querySelector('#piggy-expense').onclick=()=>openMovement({source:id});document.querySelector('#piggy-history').onclick=()=>openPiggyHistory(id);document.querySelector('#share-piggy')?.addEventListener('click',()=>openSharePiggy(id));document.querySelector('#delete-piggy')?.addEventListener('click',()=>deletePiggySecure(id))}
async function deletePiggySecure(id){if(!confirm('¿Eliminar esta hucha y todos sus movimientos?'))return;const {error}=await sb.rpc('delete_piggy_secure',{p_piggy_id:id});if(error)return err(error);closeModal();await refreshAll();renderShell();toast('Hucha eliminada')}
function openPiggyHistory(id){closeModal();const p=state.piggies.find(x=>x.id===id),rows=state.piggyTx.filter(t=>t.piggy_id===id);modal(`<div class="modal-head"><div><h3>Movimientos · ${esc(p?.name||'Hucha')}</h3></div><button class="close-btn" data-close>×</button></div><div class="transaction-list modal-list">${rows.map(t=>`<article class="tx-card"><div class="tx-icon ${t.kind}">${kindIcon(t.kind)}</div><div class="tx-main"><strong>${esc(t.concept)}</strong><small>${esc(t.profiles?.display_name||t.profiles?.email||'Usuario')} · ${dateFmt(t.occurred_on)}</small></div><div class="tx-end"><b>${money(t.amount_cents)}</b><div class="tx-buttons"><button class="mini-btn" data-edit-piggy="${t.id}">Editar</button>${canDeletePiggyTx(t,p)?`<button class="mini-btn danger" data-delete-piggy-tx="${t.id}">Borrar</button>`:''}</div></div></article>`).join('')||'<div class="empty">Sin movimientos</div>'}</div>`);document.querySelectorAll('[data-edit-piggy]').forEach(b=>b.addEventListener('click',()=>{const t=state.piggyTx.find(x=>x.id===b.dataset.editPiggy);openPiggyTx(id,t.kind,t)}));document.querySelectorAll('[data-delete-piggy-tx]').forEach(b=>b.addEventListener('click',()=>deletePiggyTxSecure(id,b.dataset.deletePiggyTx)))}
async function deletePiggyTxSecure(piggyId,txId){if(!confirm('¿Eliminar este movimiento de la hucha?'))return;const {error}=await sb.rpc('delete_piggy_transaction_secure',{p_transaction_id:txId});if(error)return err(error);closeModal();await refreshAll();renderShell();openPiggyHistory(piggyId)}
function openSharePiggy(id){closeModal();modal(`<form id="share-form"><div class="modal-head"><div><h3>Invitar a la hucha</h3><p class="muted">El usuario deberá aceptar la invitación.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Enviar invitación</button></div></form>`);document.querySelector('#share-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{error}=await sb.rpc('invite_shared_resource',{p_resource_type:'piggy',p_resource_id:id,p_email:String(fd.get('email')).trim().toLowerCase()});if(error)return err(error);closeModal();toast('Invitación enviada')})}
function openShareGoal(id){closeModal();modal(`<form id="share-goal-form"><div class="modal-head"><div><h3>Invitar al objetivo</h3><p class="muted">El usuario deberá aceptar la invitación.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Enviar invitación</button></div></form>`);document.querySelector('#share-goal-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),{error}=await sb.rpc('invite_shared_resource',{p_resource_type:'goal',p_resource_id:id,p_email:String(fd.get('email')).trim().toLowerCase()});if(error)return err(error);closeModal();toast('Invitación enviada')})}
function openFolderMenu(id){const f=state.folders.find(x=>x.id===id);modal(`<div class="modal-head"><div><h3>${esc(f.name)}</h3></div><button class="close-btn" data-close>×</button></div><div class="menu-list"><button class="btn" id="folder-add">Añadir movimiento</button><button class="btn" id="folder-view">Ver movimientos</button></div>`);document.querySelector('#folder-add').onclick=()=>{closeModal();openMovement({folder_id:id})};document.querySelector('#folder-view').onclick=()=>{closeModal();state.folderFilter=id;state.filters={q:'',from:'',to:'',amount:'',kind:'all'};state.tab='activity';renderShell()}}

function openNotifications(){const invites=state.invitations.map(i=>`<div class="list-row unread"><div><div class="list-title">Invitación a ${i.resource_type==='piggy'?'hucha':'objetivo'}</div><div class="list-meta">Pendiente de respuesta</div></div><div class="invite-actions"><button class="mini-btn" data-accept-invite="${i.id}">Aceptar</button><button class="mini-btn danger" data-reject-invite="${i.id}">Rechazar</button></div></div>`).join('');modal(`<div class="modal-head"><div><h3>Avisos</h3><p class="muted">${state.notifications.filter(n=>!n.read_at).length} sin leer</p></div><button class="close-btn" data-close>×</button></div><div class="list modal-list">${invites}${state.notifications.map(n=>`<div class="list-row ${n.read_at?'':'unread'}"><div><div class="list-title">${esc(n.title)}</div><div class="list-meta">${esc(n.body)} · ${dateFmt(n.created_at?.slice(0,10))}</div></div><button class="mini-btn" data-read="${n.id}">${n.read_at?'Leído':'Marcar'}</button></div>`).join('')||(!invites?'<div class="empty">No hay avisos.</div>':'')}</div>`);document.querySelectorAll('[data-accept-invite]').forEach(b=>b.addEventListener('click',()=>respondInvite(b.dataset.acceptInvite,true)));document.querySelectorAll('[data-reject-invite]').forEach(b=>b.addEventListener('click',()=>respondInvite(b.dataset.rejectInvite,false)));document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',async()=>{await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',b.dataset.read);closeModal();await refreshAll();renderShell();openNotifications()}))}
async function respondInvite(id,accept){const {error}=await sb.rpc('respond_shared_invitation',{p_invitation_id:id,p_accept:accept});if(error)return err(error);closeModal();await refreshAll();renderShell();toast(accept?'Invitación aceptada':'Invitación rechazada')}

function openAccountMenu(){modal(`<div class="modal-head"><div><h3>${esc(state.profile.display_name||state.profile.email)}</h3><p class="muted">${esc(state.profile.email)}</p></div><button class="close-btn" data-close>×</button></div><div class="menu-list">${state.profile.role==='admin'?'<button class="btn" id="admin-panel">Administración</button>':''}<button class="btn" id="change-password">Cambiar contraseña</button>${installPrompt?'<button class="btn" id="install-app">Instalar aplicación</button>':''}<button class="btn danger" id="logout">Cerrar sesión</button></div>`);document.querySelector('#logout').onclick=()=>sb.auth.signOut();document.querySelector('#change-password').onclick=openChangePassword;document.querySelector('#install-app')?.addEventListener('click',async()=>{installPrompt.prompt();await installPrompt.userChoice;installPrompt=null});document.querySelector('#admin-panel')?.addEventListener('click',openAdmin)}
function openChangePassword(){closeModal();modal(`<form id="password-form"><div class="modal-head"><div><h3>Cambiar contraseña</h3><p class="muted">La sesión seguirá protegida por Supabase Auth.</p></div><button type="button" class="close-btn" data-close>×</button></div><div class="field"><label>Nueva contraseña</label><input name="password" type="password" minlength="10" autocomplete="new-password" required></div><div class="field"><label>Repetir contraseña</label><input name="confirm" type="password" minlength="10" autocomplete="new-password" required></div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Actualizar</button></div></form>`);document.querySelector('#password-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),pw=String(fd.get('password'));if(pw!==fd.get('confirm'))return toast('Las contraseñas no coinciden',true);const {error}=await sb.auth.updateUser({password:pw});if(error)return err(error);closeModal();toast('Contraseña actualizada')})}
function openAdmin(){closeModal();modal(`<div class="modal-head"><div><h3>Administración</h3><p class="muted">Crear usuarios y conceder permisos</p></div><button class="close-btn" data-close>×</button></div><button class="btn primary full" id="create-user">Nuevo usuario</button><div class="admin-table modal-list">${state.users.map(u=>{const p=u.user_permissions?.[0]||{};return `<article class="user-card" data-user-card="${u.id}"><div class="list-row"><div><div class="list-title">${esc(u.display_name||u.email)}</div><div class="list-meta">${esc(u.email)}</div></div><select data-admin-role><option value="user" ${u.role==='user'?'selected':''}>Usuario</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrador</option></select></div><div class="permission-grid">${[['active','Activo',u],['can_create_piggy','Crear huchas',p],['can_create_shared','Crear compartidas',p],['can_add_income','Añadir ingresos',p],['can_add_expense','Añadir gastos',p],['can_manage_members','Gestionar miembros',p]].map(([k,l,o])=>`<label class="check"><input type="checkbox" data-perm="${k}" ${o[k]?'checked':''}>${l}</label>`).join('')}</div><button class="btn primary full" data-save-user="${u.id}">Guardar permisos</button></article>`}).join('')}</div>`);document.querySelector('#create-user').onclick=openCreateUser;document.querySelectorAll('[data-save-user]').forEach(b=>b.addEventListener('click',()=>saveUserV3(b.dataset.saveUser)))}
async function saveUserV3(id){const card=document.querySelector(`[data-user-card="${id}"]`),role=card.querySelector('[data-admin-role]').value,v={};card.querySelectorAll('[data-perm]').forEach(x=>v[x.dataset.perm]=x.checked);const {error}=await sb.rpc('admin_update_user',{p_user_id:id,p_role:role,p_active:v.active,p_can_create_piggy:v.can_create_piggy,p_can_create_shared:v.can_create_shared,p_can_add_income:v.can_add_income,p_can_add_expense:v.can_add_expense,p_can_manage_members:v.can_manage_members});if(error)return err(error);toast('Permisos actualizados');await refreshAll();closeModal();openAdmin()}
