(function(){
  'use strict';
  const A=window.A2C;
  const B=A.budgets={};
  B.spent=budget=>A.state.transactions.filter(row=>row.kind==='expense'&&String(row.occurred_on||'').slice(0,7)===budget.period_month&&(row.budget_category||A.classify(row.concept||row.merchant))===budget.category_key).reduce((sum,row)=>sum+Number(row.amount_cents||0),0);
  B.rowMarkup=budget=>{const spent=B.spent(budget);const pct=budget.amount_cents?Math.min(100,spent/Number(budget.amount_cents)*100):0;const definition=A.categoryDefinitions[budget.category_key]||A.categoryDefinitions.other;return `<button class="budget-row" data-action="edit-budget" data-id="${budget.id}"><span class="category-icon">${A.icon(definition.icon,18)}</span><div class="budget-main"><div><strong>${A.escape(budget.name)}</strong><b>${A.money(spent)} / ${A.money(budget.amount_cents)}</b></div><div class="progress-track"><i style="width:${pct}%"></i></div><small>${A.escape(definition.name)} · ${Math.round(pct)}% consumido</small></div></button>`;};
  B.render=()=>{const current=A.state.budgets.filter(row=>row.active&&row.period_month===A.monthKey());const future=A.state.budgets.filter(row=>row.period_month>A.monthKey());return `${A.ui.sectionTitle('Presupuestos','Límites mensuales por categoría','<button class="btn small primary" data-action="new-budget">'+A.icon('plus',15)+' Añadir</button>')}${current.length?`<div class="budget-list">${current.map(B.rowMarkup).join('')}</div>`:A.ui.empty('No hay presupuestos activos','Añade un límite para controlar una categoría.')}${future.length?`<details class="future-budgets"><summary>Presupuestos futuros (${future.length})</summary><div class="budget-list">${future.map(B.rowMarkup).join('')}</div></details>`:''}`;};
  B.openForm=budget=>{const editing=Boolean(budget?.id);A.ui.modal(`<form id="budget-form" class="stack-form"><div class="modal-head"><div><h2>${editing?'Editar':'Nuevo'} presupuesto</h2><p>Controla una categoría durante uno o varios meses.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="field"><label>Nombre</label><input name="name" required value="${A.escape(budget?.name||'')}"></div><div class="field"><label>Categoría</label><select name="category">${Object.entries(A.categoryDefinitions).filter(([key])=>key!=='other').map(([key,item])=>`<option value="${key}" ${budget?.category_key===key?'selected':''}>${item.name}</option>`).join('')}</select></div><div class="form-grid two"><div class="field"><label>Importe máximo (€)</label><input name="amount" inputmode="decimal" required value="${budget?Number(budget.amount_cents)/100:''}"></div><div class="field"><label>Mes inicial</label><input name="month" type="month" required value="${A.escape(budget?.period_month||A.monthKey())}"></div></div><div class="field"><label>Número de meses</label><input name="months" type="number" min="1" max="36" value="1" ${editing?'disabled':''}></div><label class="option-card"><input name="active" type="checkbox" ${budget?.active===false?'':'checked'}><span class="option-icon">${A.icon('budget',20)}</span><span><b>Presupuesto activo</b><small>Aparecerá en inicio y en el widget.</small></span></label><div class="actions">${editing?'<button type="button" class="btn danger" id="delete-budget">'+A.icon('trash',16)+' Eliminar</button>':''}<button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);
    const form=A.modalRoot.querySelector('#budget-form');form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const base={user_id:A.state.user.id,name:String(form.elements.name.value).trim(),category_key:form.elements.category.value,amount_cents:A.toCents(form.elements.amount.value),active:form.elements.active.checked,updated_at:new Date().toISOString()};if(!base.name||base.amount_cents<=0)throw new Error('Nombre o importe no válido.');if(editing){const result=await A.sb.from('budgets_v67').update({...base,period_month:form.elements.month.value}).eq('id',budget.id).eq('user_id',A.state.user.id);if(result.error)throw result.error;}else{const count=Math.max(1,Math.min(36,Number(form.elements.months.value||1)));const start=new Date(`${form.elements.month.value}-01T12:00:00`);const rows=[];const series=crypto.randomUUID?.()||A.unique('budget');for(let index=0;index<count;index++){const date=new Date(start.getFullYear(),start.getMonth()+index,1,12);rows.push({...base,period_month:A.monthKey(date),series_id:series});}const result=await A.sb.from('budgets_v67').insert(rows);if(result.error)throw result.error;}await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});A.toast('Presupuesto guardado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});
    A.modalRoot.querySelector('#delete-budget')?.addEventListener('click',()=>{A.closeModal();B.delete(budget.id);});
  };
  B.delete=id=>A.ui.confirm({title:'Eliminar presupuesto',message:'Los movimientos registrados no se eliminarán.',confirmLabel:'Eliminar',danger:true,onConfirm:async()=>{const result=await A.sb.from('budgets_v67').delete().eq('id',id).eq('user_id',A.state.user.id);if(result.error)throw result.error;await A.store.load({force:true});A.ui.render({preserveScroll:true});A.toast('Presupuesto eliminado.');}});
  A.ui.action('new-budget',()=>B.openForm());A.ui.action('edit-budget',({data})=>B.openForm(A.state.budgets.find(row=>String(row.id)===String(data.id))));
})();
