(function(){
  'use strict';
  const A=window.A2C;
  const B=A.budgets={
    spent(budget){return A.state.transactions.filter(row=>row.kind==='expense'&&String(row.occurred_on||'').slice(0,7)===budget.period_month&&(row.budget_category||A.classify(row.concept||row.merchant))===budget.category_key).reduce((sum,row)=>sum+Number(row.amount_cents||0),0);},
    rowMarkup(budget){const spent=B.spent(budget);const pct=budget.amount_cents?Math.min(100,spent/Number(budget.amount_cents)*100):0;return `<article class="budget-row clickable" data-budget="${budget.id}"><div class="budget-row-head"><div><strong>${A.escape(budget.name)}</strong><small>${A.escape(A.categoryDefinitions[budget.category_key]?.name||budget.category_key)} · ${A.escape(budget.period_month)}</small></div><b>${A.money(spent)} / ${A.money(budget.amount_cents)}</b></div><div class="progress"><i style="width:${pct}%"></i></div><small>${Math.round(pct)}% consumido</small></article>`;},
    render(){const current=A.state.budgets.filter(row=>row.active&&row.period_month===A.monthKey());const future=A.state.budgets.filter(row=>row.period_month>A.monthKey());return `<div class="card-title"><div><h2>Presupuestos</h2><p>Límites mensuales por categoría.</p></div><button class="btn primary" id="new-budget">＋ Añadir</button></div>${current.length?`<div class="grid">${current.map(B.rowMarkup).join('')}</div>`:A.ui.empty('No hay presupuestos activos este mes.')}${future.length?`<details style="margin-top:12px"><summary>Presupuestos futuros (${future.length})</summary><div class="grid" style="margin-top:8px">${future.map(B.rowMarkup).join('')}</div></details>`:''}`;},
    bind(){if(A.state.page!=='tools'||A.state.tool!=='budgets')return;A.root.querySelector('#new-budget')?.addEventListener('click',()=>B.openForm());A.root.querySelectorAll('[data-budget]').forEach(row=>row.addEventListener('click',()=>B.openForm(A.state.budgets.find(b=>String(b.id)===String(row.dataset.budget)))));},
    openForm(budget=null){
      const editing=Boolean(budget?.id);A.modal(`<form id="budget-form"><div class="modal-head"><div><h2>${editing?'Editar':'Nuevo'} presupuesto</h2><p>Controla el gasto de una categoría durante uno o varios meses.</p></div><button class="modal-close" data-close>×</button></div><div class="field"><label>Nombre</label><input name="name" required value="${A.escape(budget?.name||'')}"></div><div class="field"><label>Categoría</label><select name="category">${Object.entries(A.categoryDefinitions).filter(([key])=>key!=='other').map(([key,item])=>`<option value="${key}" ${budget?.category_key===key?'selected':''}>${item.icon} ${item.name}</option>`).join('')}</select></div><div class="field-row"><div class="field"><label>Importe máximo (€)</label><input name="amount" inputmode="decimal" required value="${budget?Number(budget.amount_cents)/100:''}"></div><div class="field"><label>Mes inicial</label><input name="month" type="month" required value="${A.escape(budget?.period_month||A.monthKey())}"></div></div><div class="field"><label>Número de meses</label><input name="months" type="number" min="1" max="36" value="1" ${editing?'disabled':''}></div><label class="check-row"><input name="active" type="checkbox" ${budget?.active===false?'':'checked'}><span><b>Presupuesto activo</b><small>Aparecerá en el panel y en el widget.</small></span></label><div class="actions">${editing?'<button type="button" class="btn danger" id="delete-budget">Eliminar</button>':''}<button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);
      const form=A.modalRoot.querySelector('#budget-form');form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const base={user_id:A.state.user.id,name:String(form.elements.name.value).trim(),category_key:form.elements.category.value,amount_cents:A.toCents(form.elements.amount.value),active:form.elements.active.checked,updated_at:new Date().toISOString()};if(!base.name||base.amount_cents<=0)throw new Error('Nombre o importe no válido.');if(editing){const result=await A.sb.from('budgets_v67').update({...base,period_month:form.elements.month.value}).eq('id',budget.id);if(result.error)throw result.error;}else{const count=Math.max(1,Math.min(36,Number(form.elements.months.value||1)));const start=new Date(`${form.elements.month.value}-01T12:00:00`);const rows=[];const series=crypto.randomUUID?.()||A.unique('budget');for(let index=0;index<count;index++){const date=new Date(start.getFullYear(),start.getMonth()+index,1,12);rows.push({...base,period_month:A.monthKey(date),series_id:series});}const result=await A.sb.from('budgets_v67').insert(rows);if(result.error)throw result.error;}await A.refresh(false);A.closeModal();A.ui.render();A.toast('Presupuesto guardado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});A.modalRoot.querySelector('#delete-budget')?.addEventListener('click',()=>A.ui.confirm({title:'Eliminar presupuesto',message:'No se eliminarán movimientos.',danger:true,confirmLabel:'Eliminar',onConfirm:async()=>{const result=await A.sb.from('budgets_v67').delete().eq('id',budget.id);if(result.error)throw result.error;await A.refresh(false);A.ui.render();}}));}
  };
})();
