(function(){
  'use strict';
  const A=window.A2C;
  const M=A.messages={activeConversation:null,activeFriend:null,poll:null,
    async load(silent=false){
      if(!A.state.user)return;
      try{A.state.conversations=await A.rpc('a2c_v7_list_conversations');A.state.friends=await A.rpc('a2c_v7_list_friends');if(!silent&&A.state.page==='messages')A.ui.render();}
      catch(error){console.warn(error);if(!silent)A.toast('No se pudieron actualizar los mensajes.',true);}
    },
    render(){
      const requests=A.store.friendRequests();const unread=A.state.conversations.reduce((sum,row)=>sum+Number(row.unread_count||0),0);
      return `${A.ui.header('Social','Mensajes',unread?`${unread} mensaje${unread===1?'':'s'} sin leer`:'Conversaciones privadas y gastos compartidos','<button class="btn primary" id="find-friend">＋ Amigo</button>')}
        ${requests.length?`<section class="card" style="margin-bottom:12px"><div class="card-title"><div><h2>Solicitudes de amistad</h2><p>${requests.length} pendiente${requests.length===1?'':'s'}</p></div></div><div class="list">${requests.map(request=>{const profile=A.store.profileById(request.requester_id)||{};return `<div class="list-row">${A.avatar(profile)}<div class="list-row-main"><strong>${A.escape(profile.display_name||profile.username||'Usuario')}</strong><small>@${A.escape(profile.username||'usuario')}</small></div><button class="btn small success" data-friend-accept="${request.id}">Aceptar</button><button class="btn small danger" data-friend-reject="${request.id}">Rechazar</button></div>`;}).join('')}</div></section>`:''}
        <section class="card"><div class="card-title"><div><h2>Conversaciones</h2><p>Los mensajes se guardan cifrados en el servidor.</p></div></div>${A.state.conversations.length?`<div class="list">${A.state.conversations.map(row=>`<div class="list-row clickable" data-conversation="${row.conversation_id}" data-friend="${row.friend_id}">${A.avatar(row)}<div class="list-row-main"><strong>${A.escape(row.display_name||row.username||'Usuario')}</strong><small>${A.escape(row.last_message||'Inicia la conversación')}</small></div><div class="list-row-value"><small>${row.last_message_at?new Date(row.last_message_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):''}</small>${Number(row.unread_count||0)>0?`<span class="badge danger">${row.unread_count}</span>`:''}</div></div>`).join('')}</div>`:A.ui.empty('Todavía no tienes conversaciones. Añade un amigo para empezar.')}</section>
        <section class="card" style="margin-top:12px"><div class="card-title"><div><h2>Amigos</h2><p>${A.state.friends.length} contacto${A.state.friends.length===1?'':'s'}</p></div></div>${A.state.friends.length?`<div class="grid grid-2">${A.state.friends.map(friend=>`<button class="list-row" data-chat-friend="${friend.id}">${A.avatar(friend)}<span class="list-row-main"><strong>${A.escape(friend.display_name||friend.username)}</strong><small>@${A.escape(friend.username||'usuario')}</small></span><span>›</span></button>`).join('')}</div>`:A.ui.empty('Busca amigos mediante su @usuario.')}</section>`;
    },
    bind(){
      if(A.state.page!=='messages')return;
      A.root.querySelector('#find-friend')?.addEventListener('click',M.openSearch);
      A.root.querySelectorAll('[data-conversation]').forEach(row=>row.addEventListener('click',()=>M.openChat(row.dataset.conversation,row.dataset.friend)));
      A.root.querySelectorAll('[data-chat-friend]').forEach(row=>row.addEventListener('click',async()=>{try{const id=await A.rpc('a2c_v7_get_conversation',{p_friend_id:row.dataset.chatFriend});M.openChat(id,row.dataset.chatFriend);}catch(error){A.toast(error.message,true);}}));
      A.root.querySelectorAll('[data-friend-accept]').forEach(button=>button.addEventListener('click',()=>M.respondRequest(button.dataset.friendAccept,true)));
      A.root.querySelectorAll('[data-friend-reject]').forEach(button=>button.addEventListener('click',()=>M.respondRequest(button.dataset.friendReject,false)));
    },
    async respondRequest(id,accept){try{await A.rpc('a2c_v7_respond_friend_request',{p_friendship_id:id,p_accept:accept});await A.refresh(false);await M.load(true);A.ui.render();A.toast(accept?'Amistad aceptada.':'Solicitud rechazada.');}catch(error){A.toast(error.message,true);}},
    openSearch(){
      A.modal(`<form id="friend-search-form"><div class="modal-head"><div><h2>Buscar amigos</h2><p>Introduce el @usuario exacto o sus primeras letras.</p></div><button class="modal-close" data-close>×</button></div><div class="field"><label>@usuario</label><input name="query" required placeholder="@usuario" autocomplete="off"></div><button class="btn primary full">Buscar</button><div id="friend-results" style="margin-top:12px"></div></form>`);
      const form=A.modalRoot.querySelector('#friend-search-form');form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true,'Buscando…');try{const rows=await A.rpc('a2c_v7_search_people',{p_query:form.elements.query.value});const container=A.modalRoot.querySelector('#friend-results');container.innerHTML=rows.length?`<div class="list">${rows.map(row=>`<div class="list-row">${A.avatar(row)}<div class="list-row-main"><strong>${A.escape(row.display_name||row.username)}</strong><small>@${A.escape(row.username)}</small></div>${row.friendship_status==='accepted'?'<span class="badge success">Amigo</span>':row.friendship_status==='pending'?'<span class="badge warning">Pendiente</span>':`<button class="btn small primary" data-add-friend="${row.id}">Añadir</button>`}</div>`).join('')}</div>`:A.ui.empty('No se encontraron usuarios.');container.querySelectorAll('[data-add-friend]').forEach(add=>add.addEventListener('click',async()=>{try{await A.rpc('a2c_v7_send_friend_request',{p_user_id:add.dataset.addFriend});add.replaceWith(Object.assign(document.createElement('span'),{className:'badge warning',textContent:'Pendiente'}));A.toast('Solicitud enviada.');}catch(error){A.toast(error.message,true);}}));}catch(error){A.toast(error.message,true);}finally{A.setBusy(button,false);}});
    },
    async openChat(conversationId,friendId){
      try{
        const friend=A.state.friends.find(row=>String(row.id)===String(friendId))||A.store.profileById(friendId)||{};
        const [messages,shares]=await Promise.all([A.rpc('a2c_v7_list_messages',{p_conversation_id:conversationId,p_limit:300}),A.rpc('a2c_v7_conversation_shares',{p_conversation_id:conversationId})]);
        M.activeConversation=conversationId;M.activeFriend=friendId;
        const shareMap=new Map(shares.map(row=>[String(row.id),row]));
        A.modal(`<div class="chat-layout"><header class="chat-header"><button class="icon-button" data-close>‹</button>${A.avatar(friend)}<div><strong>${A.escape(friend.display_name||friend.username||'Conversación')}</strong><small>@${A.escape(friend.username||'usuario')}</small></div></header><div class="chat-body" id="chat-body">${messages.map(message=>message.message_type==='shared_expense'&&message.related_share_id?M.shareCard(shareMap.get(String(message.related_share_id)),message):`<article class="bubble ${message.mine?'mine':''}"><p>${A.escape(message.body)}</p><small>${new Date(message.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}</small></article>`).join('')||A.ui.empty('Escribe el primer mensaje.')}</div><form class="chat-compose" id="chat-form"><textarea name="body" maxlength="4000" required placeholder="Mensaje"></textarea><button aria-label="Enviar">➤</button></form></div>`,true);
        const body=A.modalRoot.querySelector('#chat-body');body.scrollTop=body.scrollHeight;
        A.modalRoot.querySelector('#chat-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const button=event.submitter;const text=String(form.elements.body.value||'').trim();if(!text)return;button.disabled=true;try{await A.rpc('a2c_v7_send_message',{p_friend_id:friendId,p_body:text});form.reset();await M.load(true);await M.openChat(conversationId,friendId);}catch(error){A.toast(error.message,true);button.disabled=false;}});
        A.modalRoot.querySelectorAll('[data-pay-share]').forEach(button=>button.addEventListener('click',()=>M.openPay(button.dataset.payShare,conversationId,friendId)));
        A.modalRoot.querySelectorAll('[data-manage-share]').forEach(button=>button.addEventListener('click',()=>M.openManage(shareMap.get(button.dataset.manageShare),conversationId,friendId)));
      }catch(error){A.toast(error.message,true);}
    },
    shareCard(share,message){
      if(!share)return `<article class="share-message old"><strong>Gasto compartido anterior</strong><small>Esta versión ya no está activa.</small></article>`;
      const old=['superseded','cancelled'].includes(share.status);const labels={pending:'Pendiente',paid:'Pagado',settled:'Liquidado manualmente',superseded:'Versión anterior',cancelled:'Cancelado'};
      return `<article class="share-message ${old?'old':''}"><div class="share-message-head"><span class="kind-icon expense">⇄</span><div><small>GASTO COMPARTIDO · VERSIÓN ${share.version}</small><strong>${A.escape(share.concept||'Gasto compartido')}</strong><small>Total ${A.money(share.total_cents)} · Parte ${A.money(share.amount_cents)}</small></div><span class="badge ${share.status==='pending'?'warning':share.status==='paid'||share.status==='settled'?'success':'muted'}">${labels[share.status]||share.status}</span></div>${old?'<div class="notice" style="margin-top:8px">Esta versión ya no permite acciones.</div>':`<div class="share-message-actions">${share.can_pay?`<button class="btn small primary" data-pay-share="${share.id}">Pagar</button>`:''}${share.can_manage?`<button class="btn small" data-manage-share="${share.id}">Gestionar</button>`:''}</div>`}</article>`;
    },
    openPay(id,conversationId,friendId){const share=A.state.shares.find(row=>String(row.id)===String(id));A.modal(`<form id="pay-share-form"><div class="modal-head"><div><h2>Pagar gasto compartido</h2><p>El importe se descontará de la cuenta elegida y se abonará al creador.</p></div><button class="modal-close" data-close>×</button></div><div class="card balance-card"><small>Importe pendiente</small><div class="big-number">${A.money(share?.amount_cents||0)}</div></div><div class="field" style="margin-top:12px"><label>Cuenta</label><select name="resource"><option value="">Cuenta principal</option>${A.state.resources.map(resource=>`<option value="${resource.id}">${A.escape(resource.name)}</option>`).join('')}</select></div><div class="field"><label>Método</label><select name="method"><option value="bank">Banco / tarjeta</option><option value="cash">Efectivo</option></select></div><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Pagar ahora</button></div></form>`);A.modalRoot.querySelector('#pay-share-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true,'Pagando…');try{await A.rpc('a2c_v7_pay_shared_expense',{p_share_id:id,p_resource_id:event.currentTarget.elements.resource.value||null,p_payment_method:event.currentTarget.elements.method.value});await A.refresh(false);await M.load(true);A.closeModal();A.toast('Pago realizado.');M.openChat(conversationId,friendId);}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});},
    openManage(share,conversationId,friendId){if(!share)return;A.modal(`<div class="modal-head"><div><h2>Gestionar reparto</h2><p>${A.escape(share.concept||'Gasto compartido')} · ${A.money(share.amount_cents)}</p></div><button class="modal-close" data-close>×</button></div><div class="notice">Editar crea una nueva versión. Liquidar manualmente aumenta tu saldo sin descontar al amigo.</div><div class="actions"><button class="btn" id="manage-edit">Editar importe</button><button class="btn success" id="manage-settle">Liquidar manualmente</button><button class="btn danger" id="manage-cancel">Cancelar reparto</button></div>`);A.modalRoot.querySelector('#manage-edit').addEventListener('click',()=>A.transactions.editShare(share.id));A.modalRoot.querySelector('#manage-settle').addEventListener('click',()=>A.transactions.settleShare(share.id));A.modalRoot.querySelector('#manage-cancel').addEventListener('click',()=>A.transactions.cancelShare(share.id));}
  };
  A.ui.registerPage('messages',M.render);
})();
