(function(){
  'use strict';
  const A=window.A2C;
  const M=A.messages={conversations:[],activeConversation:null,activeFriend:null,lastLoadedAt:0,loadingPromise:null,chatTimer:null};
  M.load=async({force=false}={})=>{
    if(!A.state.user)return [];
    if(M.loadingPromise)return M.loadingPromise;
    if(!force&&Date.now()-M.lastLoadedAt<15000)return M.conversations;
    M.loadingPromise=(async()=>{try{M.conversations=await A.rpc('a2c_v7_list_conversations');M.lastLoadedAt=Date.now();return M.conversations;}catch(error){console.warn(error);M.conversations=[];return [];}finally{M.loadingPromise=null;}})();
    return M.loadingPromise;
  };
  M.render=()=>{const requests=A.store.friendRequests();return `${A.ui.header('Mensajes','Conversaciones','Habla con tus amigos y gestiona gastos compartidos','<button class="btn primary" data-action="find-friend">'+A.icon('userAdd',17)+' Buscar amigo</button>')}
    ${requests.length?`<section class="card request-card">${A.ui.sectionTitle('Solicitudes pendientes',`${requests.length} solicitud${requests.length===1?'':'es'}`)}<div class="friend-list">${requests.map(request=>{const person=A.store.profileById(request.requester_id)||{};return `<div class="friend-row">${A.avatar(person)}<div><strong>${A.escape(person.display_name||person.username||'Usuario')}</strong><small>@${A.escape(person.username||'usuario')}</small></div><button class="btn tiny secondary" data-action="friend-reject" data-id="${request.id}">Rechazar</button><button class="btn tiny primary" data-action="friend-accept" data-id="${request.id}">Aceptar</button></div>`;}).join('')}</div></section>`:''}
    <section class="card messages-card">${A.ui.sectionTitle('Conversaciones','Mensajes y gastos compartidos')}${M.conversations.length?`<div class="conversation-list">${M.conversations.map(row=>`<button class="conversation-row" data-action="open-chat" data-conversation="${row.conversation_id}" data-friend="${row.friend_id}">${A.avatar(row)}<span><strong>${A.escape(row.display_name||row.username||'Conversación')}</strong><small>${A.escape(row.last_message||'Sin mensajes')}</small></span><time>${row.last_message_at?new Date(row.last_message_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):''}</time>${Number(row.unread_count)>0?`<em>${row.unread_count>9?'9+':row.unread_count}</em>`:''}</button>`).join('')}</div>`:A.ui.empty('No hay conversaciones','Busca un amigo por su @usuario para empezar.')}</section>
    <section class="card friends-card">${A.ui.sectionTitle('Amigos','Contactos disponibles')}${A.state.friends.length?`<div class="friend-grid">${A.state.friends.map(friend=>`<button class="friend-card" data-action="start-chat" data-friend="${friend.id}">${A.avatar(friend)}<span><strong>${A.escape(friend.display_name||friend.username)}</strong><small>@${A.escape(friend.username||'usuario')}</small></span>${A.icon('chevron',18)}</button>`).join('')}</div>`:A.ui.empty('Aún no tienes amigos','Usa el buscador para enviar una solicitud.')}</section>`;};
  M.respond=async(id,accept)=>{await A.rpc('a2c_v7_respond_friend_request',{p_friendship_id:id,p_accept:accept});await A.store.load({force:true});await M.load({force:true});A.ui.render({preserveScroll:true});A.toast(accept?'Amistad aceptada.':'Solicitud rechazada.');};
  M.openSearch=()=>{A.ui.modal(`<form id="friend-search-form" class="stack-form"><div class="modal-head"><div><h2>Buscar amigos</h2><p>Introduce el @usuario exacto o sus primeras letras.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="field"><label>@usuario</label><input name="query" required placeholder="@usuario" autocomplete="off"></div><button class="btn primary full">${A.icon('search',17)} Buscar</button><div id="friend-results"></div></form>`);const form=A.modalRoot.querySelector('#friend-search-form');form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true,'Buscando…');try{const rows=await A.rpc('a2c_v7_search_people',{p_query:form.elements.query.value});const container=A.modalRoot.querySelector('#friend-results');container.innerHTML=rows.length?`<div class="friend-list">${rows.map(row=>`<div class="friend-row">${A.avatar(row)}<div><strong>${A.escape(row.display_name||row.username)}</strong><small>@${A.escape(row.username)}</small></div>${row.friendship_status==='accepted'?'<span class="status-pill">Amigo</span>':row.friendship_status==='pending'?'<span class="status-pill">Pendiente</span>':`<button class="btn tiny primary" data-add-friend="${row.id}">Añadir</button>`}</div>`).join('')}</div>`:A.ui.empty('No se encontraron usuarios');container.querySelectorAll('[data-add-friend]').forEach(add=>add.addEventListener('click',async()=>{try{await A.rpc('a2c_v7_send_friend_request',{p_user_id:add.dataset.addFriend});add.replaceWith(Object.assign(document.createElement('span'),{className:'status-pill',textContent:'Pendiente'}));A.toast('Solicitud enviada.');}catch(error){A.toast(error.message,true);}}));}catch(error){A.toast(error.message,true);}finally{A.setBusy(button,false);}});};
  M.startChat=async friendId=>{const id=await A.rpc('a2c_v7_get_conversation',{p_friend_id:friendId});await M.load({force:true});M.openChat(id,friendId);};
  M.messageMarkup=message=>message.message_type==='shared_expense'&&message.related_share_id?M.shareCard(M._shareMap?.get(String(message.related_share_id)),message):`<article class="bubble ${message.mine?'mine':''}"><p>${A.escape(message.body)}</p><small>${new Date(message.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}</small></article>`;
  M.openChat=async(conversationId,friendId)=>{try{const friend=A.state.friends.find(row=>String(row.id)===String(friendId))||A.store.profileById(friendId)||{};const [messages,shares]=await Promise.all([A.rpc('a2c_v7_list_messages',{p_conversation_id:conversationId,p_limit:300}),A.rpc('a2c_v7_conversation_shares',{p_conversation_id:conversationId})]);M.activeConversation=conversationId;M.activeFriend=friendId;M._shareMap=new Map(shares.map(row=>[String(row.id),row]));A.ui.modal(`<div class="chat-layout"><header class="chat-header"><button class="icon-button" data-close>${A.icon('chevron',20,'back-icon')}</button>${A.avatar(friend)}<div><strong>${A.escape(friend.display_name||friend.username||'Conversación')}</strong><small>@${A.escape(friend.username||'usuario')}</small></div></header><div class="chat-body" id="chat-body">${messages.map(M.messageMarkup).join('')||A.ui.empty('Escribe el primer mensaje')}</div><form class="chat-compose" id="chat-form"><textarea name="body" maxlength="4000" required placeholder="Escribe un mensaje"></textarea><button aria-label="Enviar">${A.icon('send',20)}</button></form></div>`,{wide:true,className:'chat-modal'});const body=A.modalRoot.querySelector('#chat-body');body.scrollTop=body.scrollHeight;A.modalRoot.querySelector('#chat-form').addEventListener('submit',M.send);M.bindShareActions(conversationId,friendId);M.startChatRefresh();}catch(error){A.toast(error.message,true);}};
  M.refreshChat=async()=>{if(!M.activeConversation||!A.modalRoot.querySelector('#chat-body'))return;try{const [messages,shares]=await Promise.all([A.rpc('a2c_v7_list_messages',{p_conversation_id:M.activeConversation,p_limit:300}),A.rpc('a2c_v7_conversation_shares',{p_conversation_id:M.activeConversation})]);M._shareMap=new Map(shares.map(row=>[String(row.id),row]));const body=A.modalRoot.querySelector('#chat-body');const nearBottom=body.scrollHeight-body.scrollTop-body.clientHeight<80;body.innerHTML=messages.map(M.messageMarkup).join('')||A.ui.empty('Escribe el primer mensaje');if(nearBottom)body.scrollTop=body.scrollHeight;M.bindShareActions(M.activeConversation,M.activeFriend);}catch(error){console.warn(error);}};
  M.send=async event=>{event.preventDefault();const form=event.currentTarget;const button=event.submitter;const text=String(form.elements.body.value||'').trim();if(!text||button.disabled)return;button.disabled=true;try{await A.rpc('a2c_v7_send_message',{p_friend_id:M.activeFriend,p_body:text});form.reset();await Promise.all([M.load({force:true}),M.refreshChat()]);}catch(error){A.toast(error.message,true);}finally{button.disabled=false;form.elements.body.focus();}};
  M.startChatRefresh=()=>{clearInterval(M.chatTimer);M.chatTimer=setInterval(()=>{if(!document.hidden&&M.activeConversation&&A.modalRoot.querySelector('#chat-body'))M.refreshChat();},15000);};
  M.bindShareActions=(conversationId,friendId)=>{A.modalRoot.querySelectorAll('[data-pay-share]').forEach(button=>button.addEventListener('click',()=>M.openPay(button.dataset.payShare,conversationId,friendId)));A.modalRoot.querySelectorAll('[data-manage-share]').forEach(button=>button.addEventListener('click',()=>M.openManage(M._shareMap.get(button.dataset.manageShare),conversationId,friendId)));};
  M.shareCard=share=>{if(!share)return `<article class="share-message inactive"><strong>Gasto compartido anterior</strong><small>Esta versión ya no está activa.</small></article>`;const old=['superseded','cancelled'].includes(share.status);const labels={pending:'Pendiente',paid:'Pagado',settled:'Liquidado',superseded:'Versión anterior',cancelled:'Cancelado'};return `<article class="share-message ${old?'inactive':''}"><div class="share-message-head"><span class="movement-icon blue">${A.icon('transfer',19)}</span><div><small>GASTO COMPARTIDO · VERSIÓN ${share.version}</small><strong>${A.escape(share.concept||'Gasto compartido')}</strong><small>Total ${A.money(share.total_cents)} · Tu parte ${A.money(share.amount_cents)}</small></div><span class="status-pill">${labels[share.status]||share.status}</span></div>${old?'':`<div class="share-message-actions">${share.can_pay?`<button class="btn tiny primary" data-pay-share="${share.id}">Pagar</button>`:''}${share.can_manage?`<button class="btn tiny secondary" data-manage-share="${share.id}">Gestionar</button>`:''}</div>`}</article>`;};
  M.openPay=(id,conversationId,friendId)=>{const share=A.state.shares.find(row=>String(row.id)===String(id));A.ui.modal(`<form id="pay-share-form" class="stack-form"><div class="modal-head"><div><h2>Pagar gasto compartido</h2><p>Se descontará de la cuenta elegida y se abonará al creador.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="detail-amount"><span class="movement-icon blue">${A.icon('transfer',22)}</span><div><small>Importe pendiente</small><strong>${A.money(share?.amount_cents||0)}</strong></div></div><div class="field"><label>Cuenta</label><select name="resource"><option value="">Cuenta principal</option>${A.state.resources.map(row=>`<option value="${row.id}">${A.escape(row.name)}</option>`).join('')}</select></div><div class="field"><label>Método</label><select name="method"><option value="bank">Banco / tarjeta</option><option value="cash">Efectivo</option></select></div><div class="actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary">Pagar ahora</button></div></form>`);A.modalRoot.querySelector('#pay-share-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true,'Pagando…');try{await A.rpc('a2c_v7_pay_shared_expense',{p_share_id:id,p_resource_id:event.currentTarget.elements.resource.value||null,p_payment_method:event.currentTarget.elements.method.value});A.store.clearStatistics();await A.store.load({force:true});await M.load({force:true});A.closeModal();A.toast('Pago realizado.');M.openChat(conversationId,friendId);}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});};
  M.openManage=share=>{if(!share)return;A.ui.modal(`<div class="modal-head"><div><h2>Gestionar reparto</h2><p>${A.escape(share.concept||'Gasto compartido')} · ${A.money(share.amount_cents)}</p></div><button class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="info-strip">Editar crea una versión nueva. Liquidar manualmente aumenta tu saldo sin descontar al amigo.</div><div class="actions"><button class="btn secondary" data-action="edit-share" data-id="${share.id}">Editar importe</button><button class="btn primary" data-action="settle-share" data-id="${share.id}">Liquidar</button><button class="btn danger" data-action="cancel-share" data-id="${share.id}">Cancelar reparto</button></div>`);};
  A.ui.action('find-friend',M.openSearch);A.ui.action('friend-accept',({data})=>M.respond(data.id,true));A.ui.action('friend-reject',({data})=>M.respond(data.id,false));A.ui.action('start-chat',({data})=>M.startChat(data.friend));A.ui.action('open-chat',({data})=>M.openChat(data.conversation,data.friend));
  A.ui.registerPage('messages',M.render);
})();
