(function(){
  'use strict';
  const A=window.A2C;
  const P=A.profile={};
  P.render=()=>{const profile=A.state.profile||{};const pending=A.state.notifications.filter(row=>!row.read_at).length;return `${A.ui.header('Cuenta','Perfil y ajustes','Privacidad, avisos, copias y configuración')}
    <section class="profile-card">${A.avatar(profile)}<div><strong>${A.escape(profile.display_name||profile.username||profile.email||'Usuario')}</strong><small>@${A.escape(profile.username||'sin-usuario')} · ${A.escape(profile.email||'')}</small></div><button class="btn small secondary" data-action="edit-profile">${A.icon('edit',15)} Editar</button></section>
    <section class="settings-grid">
      <button class="setting-card" data-action="open-notifications"><span>${A.icon('bell',22)}</span><div><strong>Notificaciones</strong><small>${pending} aviso${pending===1?'':'s'} sin leer</small></div>${A.icon('chevron',18)}</button>
      ${window.A2CNative?`<button class="setting-card" data-action="native-settings"><span>${A.icon('wallet',22)}</span><div><strong>Detección de pagos</strong><small>Permisos, diagnóstico y pruebas</small></div>${A.icon('chevron',18)}</button>`:''}
      <button class="setting-card" data-action="export-backup"><span>${A.icon('expense',22)}</span><div><strong>Exportar copia</strong><small>Descarga tus datos en JSON</small></div>${A.icon('chevron',18)}</button>
      <button class="setting-card" data-action="choose-backup"><span>${A.icon('income',22)}</span><div><strong>Importar copia</strong><small>Restaura movimientos y herramientas</small></div>${A.icon('chevron',18)}</button>
    </section>
    <section class="card account-status">${A.ui.sectionTitle('Estado de la cuenta','Sincronización web y Android')}<div class="status-grid"><div><small>Movimientos</small><b>${A.state.transactions.length+A.state.transfers.length}</b></div><div><small>Espacios</small><b>${A.state.resources.length}</b></div><div><small>Amigos</small><b>${A.state.friends.length}</b></div><div><small>Versión</small><b>${A.VERSION}</b></div></div></section>
    <section class="card signout-card"><button class="btn danger full" data-action="sign-out">Cerrar sesión</button></section><input id="backup-file" class="hidden" type="file" accept="application/json">`;};
  P.afterRender=()=>document.querySelector('#backup-file')?.addEventListener('change',P.importBackup);
  P.openEdit=()=>{const profile=A.state.profile||{};A.ui.modal(`<form id="profile-form" class="stack-form"><div class="modal-head"><div><h2>Editar perfil</h2><p>Tu @usuario permite que tus amigos te encuentren.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="field"><label>Nombre visible</label><input name="display_name" required value="${A.escape(profile.display_name||'')}"></div><div class="field"><label>@usuario</label><input name="username" required pattern="[A-Za-z0-9._-]{3,30}" value="${A.escape(profile.username||'')}"></div><div class="field"><label>Foto</label><input name="avatar" type="file" accept="image/*"></div><div class="actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);A.modalRoot.querySelector('#profile-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const form=event.currentTarget;let avatarPath=profile.avatar_path||null;const file=form.elements.avatar.files?.[0];if(file){avatarPath=`${A.state.user.id}/avatar-${Date.now()}.${(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'')}`;const upload=await A.sb.storage.from('avatars').upload(avatarPath,file,{upsert:true});if(upload.error)throw upload.error;}const result=await A.sb.from('profiles').update({display_name:String(form.elements.display_name.value||'').trim(),username:String(form.elements.username.value||'').trim().replace(/^@/,''),avatar_path:avatarPath}).eq('id',A.state.user.id);if(result.error)throw result.error;await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});A.toast('Perfil actualizado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});};
  P.openNotifications=()=>{const rows=A.state.notifications;A.ui.modal(`<div class="modal-head"><div><h2>Notificaciones</h2><p>Avisos de pagos, amigos y gastos compartidos.</p></div><button class="modal-close" data-close>${A.icon('close',21)}</button></div>${rows.length?`<div class="notification-list">${rows.map(row=>`<article class="notification-row ${row.read_at?'':'unread'}"><span>${A.icon('bell',18)}</span><div><strong>${A.escape(row.title||'Aviso')}</strong><p>${A.escape(row.message||'')}</p><small>${new Date(row.created_at).toLocaleString('es-ES')}</small></div>${row.read_at?'':'<em>Nuevo</em>'}</article>`).join('')}</div>`:A.ui.empty('No tienes notificaciones')}<div class="actions"><button class="btn secondary" data-close>Cerrar</button>${rows.some(row=>!row.read_at)?'<button class="btn primary" id="mark-notifications">Marcar como leídas</button>':''}</div>`,{wide:true});A.modalRoot.querySelector('#mark-notifications')?.addEventListener('click',async event=>{A.setBusy(event.currentTarget,true);try{const result=await A.sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',A.state.user.id).is('read_at',null);if(result.error)throw result.error;await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});}catch(error){A.toast(error.message,true);A.setBusy(event.currentTarget,false);}});};
  P.exportBackup=()=>{const data={version:A.VERSION,exported_at:new Date().toISOString(),resources:A.state.resources,transactions:A.state.transactions,transfers:A.state.transfers,budgets:A.state.budgets,scheduled:A.state.scheduled,goals:A.state.goals};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`a2c-copia-${A.today()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);A.toast('Copia exportada.');};
  P.importBackup=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.transactions))throw new Error('El archivo no contiene una copia A2C válida.');A.ui.confirm({title:'Importar copia',message:`Se añadirán ${data.transactions.length} movimientos. Los datos actuales no se borrarán.`,confirmLabel:'Importar',onConfirm:async()=>{const resourceMap=new Map();for(const row of data.resources||[]){const payload={owner_id:A.state.user.id,type:row.type,name:row.name,description:row.description||'',target_cents:row.target_cents||null,target_date:row.target_date||null,is_shared:false};const created=await A.sb.from('resources').insert(payload).select('id').single();if(created.error)throw created.error;resourceMap.set(row.id,created.data.id);}const transactions=(data.transactions||[]).map(row=>({creator_id:A.state.user.id,resource_id:resourceMap.get(row.resource_id)||null,kind:row.kind,category_id:null,merchant:row.merchant||'',payment_method:row.payment_method||'bank',amount_cents:row.amount_cents,concept:row.concept,occurred_on:row.occurred_on,notes:row.notes||'',budget_category:row.budget_category||null,fuel_liters:row.fuel_liters||null,fuel_price_per_liter_milli:row.fuel_price_per_liter_milli||null,fuel_km:row.fuel_km||null,fuel_consumption_l100km:row.fuel_consumption_l100km||null}));if(transactions.length){const result=await A.sb.from('finance_transactions').insert(transactions);if(result.error)throw result.error;}for(const transfer of data.transfers||[]){const source=resourceMap.get(transfer.source_resource_id);const target=resourceMap.get(transfer.target_resource_id);if(source&&target)await A.rpc('a2c_v8_create_transfer',{p_source_resource_id:source,p_target_resource_id:target,p_amount_cents:transfer.amount_cents,p_concept:transfer.concept||'Traspaso importado',p_occurred_on:transfer.occurred_on||A.today(),p_scheduled_id:null});}await A.store.load({force:true});A.ui.render();A.toast('Copia importada.');}});}catch(error){A.toast(error.message,true);}};
  A.ui.action('open-notifications',P.openNotifications);A.ui.action('edit-profile',P.openEdit);A.ui.action('native-settings',()=>window.A2CNative?.openAndroidSettings?.());A.ui.action('export-backup',P.exportBackup);A.ui.action('choose-backup',()=>document.querySelector('#backup-file')?.click());A.ui.action('sign-out',A.auth.signOut);
  A.ui.registerPage('profile',P.render,P.afterRender);
})();
