(function(){
  'use strict';
  const A=window.A2C;
  const P=A.profile={
    render(){const profile=A.state.profile||{};const pending=A.state.notifications.filter(row=>!row.read_at).length;return `${A.ui.header('Cuenta','Perfil y ajustes','Privacidad, avisos, copias y configuración')}
      <section class="card"><div class="list-row" style="border:0;padding:0">${A.avatar(profile)}<div class="list-row-main"><strong>${A.escape(profile.display_name||profile.username||profile.email||'Usuario')}</strong><small>@${A.escape(profile.username||'sin-usuario')} · ${A.escape(profile.email||'')}</small></div><button class="btn small" id="edit-profile">Editar</button></div></section>
      <section class="grid grid-2" style="margin-top:12px">
        <button class="card list-row" id="profile-notifications"><span class="kind-icon">🔔</span><span class="list-row-main"><strong>Notificaciones</strong><small>${pending} aviso${pending===1?'':'s'} sin leer</small></span><span>›</span></button>
        ${window.A2CNative?`<button class="card list-row" id="native-payment-settings"><span class="kind-icon">⌁</span><span class="list-row-main"><strong>Detección de pagos</strong><small>Permisos, diagnóstico y pruebas</small></span><span>›</span></button>`:''}
        <button class="card list-row" id="backup-export"><span class="kind-icon">⇩</span><span class="list-row-main"><strong>Exportar copia</strong><small>Descarga tus datos en JSON</small></span><span>›</span></button>
        <button class="card list-row" id="backup-import"><span class="kind-icon">⇧</span><span class="list-row-main"><strong>Importar copia</strong><small>Restaura movimientos y herramientas</small></span><span>›</span></button>
      </section>
      <section class="card" style="margin-top:12px"><div class="card-title"><div><h2>Estado de la cuenta</h2><p>Sincronización web y Android</p></div></div><div class="metrics"><div class="metric-card"><small>MOVIMIENTOS</small><b>${A.state.transactions.length}</b></div><div class="metric-card"><small>ESPACIOS</small><b>${A.state.resources.length}</b></div><div class="metric-card"><small>AMIGOS</small><b>${A.state.friends.length}</b></div><div class="metric-card"><small>VERSIÓN</small><b>${A.VERSION}</b></div></div></section>
      <section class="card" style="margin-top:12px"><button class="btn danger full" id="sign-out">Cerrar sesión</button></section><input id="backup-file" class="hidden" type="file" accept="application/json">`;},
    bind(){if(A.state.page!=='profile')return;A.root.querySelector('#edit-profile')?.addEventListener('click',P.openEdit);A.root.querySelector('#profile-notifications')?.addEventListener('click',P.openNotifications);A.root.querySelector('#native-payment-settings')?.addEventListener('click',()=>window.A2CNative?.openAndroidSettings?.());A.root.querySelector('#backup-export')?.addEventListener('click',P.exportBackup);A.root.querySelector('#backup-import')?.addEventListener('click',()=>A.root.querySelector('#backup-file').click());A.root.querySelector('#backup-file')?.addEventListener('change',P.importBackup);A.root.querySelector('#sign-out')?.addEventListener('click',A.auth.signOut);},
    openEdit(){const profile=A.state.profile||{};A.modal(`<form id="profile-form"><div class="modal-head"><div><h2>Editar perfil</h2><p>Tu @usuario permite que tus amigos te encuentren.</p></div><button class="modal-close" data-close>×</button></div><div class="field"><label>Nombre visible</label><input name="display_name" required value="${A.escape(profile.display_name||'')}"></div><div class="field"><label>@usuario</label><input name="username" required pattern="[A-Za-z0-9._-]{3,30}" value="${A.escape(profile.username||'')}"></div><div class="field"><label>Foto</label><input name="avatar" type="file" accept="image/*"></div><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);A.modalRoot.querySelector('#profile-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const form=event.currentTarget;let avatarPath=profile.avatar_path||null;const file=form.elements.avatar.files?.[0];if(file){avatarPath=`${A.state.user.id}/avatar-${Date.now()}.${(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'')}`;const upload=await A.sb.storage.from('avatars').upload(avatarPath,file,{upsert:true});if(upload.error)throw upload.error;}const result=await A.sb.from('profiles').update({display_name:String(form.elements.display_name.value).trim(),username:String(form.elements.username.value).trim().replace(/^@/,''),avatar_path:avatarPath}).eq('id',A.state.user.id);if(result.error)throw result.error;await A.refresh(false);A.closeModal();A.ui.render();A.toast('Perfil actualizado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});},
    async openNotifications(){const rows=A.state.notifications;A.modal(`<div class="modal-head"><div><h2>Notificaciones</h2><p>Avisos de pagos, amigos y gastos compartidos.</p></div><button class="modal-close" data-close>×</button></div>${rows.length?`<div class="list">${rows.map(row=>`<div class="list-row"><span class="kind-icon">🔔</span><div class="list-row-main"><strong>${A.escape(row.title||'Aviso')}</strong><small>${A.escape(row.message||'')} · ${new Date(row.created_at).toLocaleString('es-ES')}</small></div>${row.read_at?'':'<span class="badge danger">Nuevo</span>'}</div>`).join('')}</div>`:A.ui.empty('No tienes notificaciones.')}<div class="actions"><button class="btn" data-close>Cerrar</button>${rows.some(row=>!row.read_at)?'<button class="btn primary" id="mark-notifications">Marcar leídas</button>':''}</div>`,true);A.modalRoot.querySelector('#mark-notifications')?.addEventListener('click',async()=>{const result=await A.sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',A.state.user.id).is('read_at',null);if(result.error)return A.toast(result.error.message,true);await A.refresh(false);A.closeModal();A.ui.render();});},
    exportBackup(){const data={version:A.VERSION,exported_at:new Date().toISOString(),resources:A.state.resources,transactions:A.state.transactions,budgets:A.state.budgets,scheduled:A.state.scheduled};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`a2c-copia-${A.today()}.json`;link.click();URL.revokeObjectURL(url);A.toast('Copia exportada.');},
    async importBackup(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.transactions))throw new Error('El archivo no contiene una copia A2C válida.');A.ui.confirm({title:'Importar copia',message:`Se añadirán ${data.transactions.length} movimientos. Los datos actuales no se borrarán.`,confirmLabel:'Importar',onConfirm:async()=>{const resourceMap=new Map();for(const resource of data.resources||[]){const payload={owner_id:A.state.user.id,type:resource.type,name:resource.name,description:resource.description||'',target_cents:resource.target_cents||null,target_date:resource.target_date||null,is_shared:false};const created=await A.sb.from('resources').insert(payload).select('id').single();if(created.error)throw created.error;resourceMap.set(resource.id,created.data.id);}const transactions=(data.transactions||[]).map(row=>({creator_id:A.state.user.id,resource_id:resourceMap.get(row.resource_id)||null,kind:row.kind,category_id:null,merchant:row.merchant||'',payment_method:row.payment_method||'bank',amount_cents:row.amount_cents,concept:row.concept,occurred_on:row.occurred_on,notes:row.notes||'',budget_category:row.budget_category||null,fuel_liters:row.fuel_liters||null,fuel_price_per_liter_milli:row.fuel_price_per_liter_milli||null,fuel_km:row.fuel_km||null,fuel_consumption_l100km:row.fuel_consumption_l100km||null}));if(transactions.length){const result=await A.sb.from('finance_transactions').insert(transactions);if(result.error)throw result.error;}await A.refresh(false);A.ui.render();A.toast('Copia importada.');}});}catch(error){A.toast(error.message,true);}}
  };
  A.ui.registerPage('profile',P.render);
})();
