(function(){
  'use strict';
  const A=window.A2C;
  const R=A.resources={};
  R.toolTabs=[['statistics','chart','Estadísticas'],['resources','folder','Huchas'],['goals','target','Objetivos'],['scheduled','calendar','Pendientes'],['budgets','budget','Presupuestos']];
  R.renderTools=()=>`${A.ui.header('Herramientas','Control y planificación','Analiza tus datos y organiza tus finanzas')}
    <div class="tool-tabs">${R.toolTabs.map(([key,icon,label])=>`<button class="tool-tab ${A.state.tool===key?'active':''}" data-action="select-tool" data-tool="${key}">${A.icon(icon,18)}<span>${label}</span></button>`).join('')}</div>
    <section class="tool-content">${A.state.tool==='statistics'?A.statistics.render():A.state.tool==='resources'?R.render():A.state.tool==='goals'?A.goals.render():A.state.tool==='scheduled'?A.scheduled.render():A.budgets.render()}</section>`;
  R.afterTools=()=>{if(A.state.tool==='statistics')A.statistics.afterRender();};
  R.render=()=>{const rows=A.state.resources.filter(row=>row.type!=='goal');return `${A.ui.sectionTitle('Huchas y carpetas','Organiza el dinero en espacios separados','<div class="section-actions"><button class="btn small secondary" data-action="new-transfer">'+A.icon('transfer',15)+' Mover saldo</button><button class="btn small primary" data-action="new-resource">'+A.icon('plus',15)+' Crear</button></div>')}${rows.length?`<div class="resource-grid">${rows.map(R.cardMarkup).join('')}</div>`:A.ui.empty('No hay espacios creados','Crea una hucha o carpeta para organizar tu dinero.')}`;};
  R.cardMarkup=row=>{const icon=row.type==='goal'?'target':row.type==='folder'?'folder':'piggy';const balance=A.resourceBalance(row.id);const progress=row.target_cents?Math.max(0,Math.min(100,balance/Number(row.target_cents)*100)):null;return `<button class="resource-card" data-action="open-resource" data-id="${row.id}"><span class="resource-icon">${A.icon(icon,24)}</span><span class="resource-main"><small>${row.type==='goal'?'Objetivo':row.type==='folder'?'Carpeta':'Hucha'}</small><strong>${A.escape(row.name)}</strong>${row.description?`<em>${A.escape(row.description)}</em>`:''}${progress!==null?`<span class="progress-track"><i style="width:${progress}%"></i></span>`:''}</span><span class="resource-balance"><b>${A.money(balance)}</b>${row.target_cents?`<small>de ${A.money(row.target_cents)}</small>`:''}</span></button>`;};
  R.openForm=resource=>{const editing=Boolean(resource?.id);A.ui.modal(`<form id="resource-form" class="stack-form"><div class="modal-head"><div><h2>${editing?'Editar espacio':'Nuevo espacio'}</h2><p>Crea una hucha o carpeta. Los objetivos se gestionan en su sección específica.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="field"><label>Tipo</label><select name="type" ${editing?'disabled':''}><option value="piggy" ${resource?.type==='piggy'?'selected':''}>Hucha</option><option value="folder" ${resource?.type==='folder'?'selected':''}>Carpeta</option></select></div><div class="field"><label>Nombre</label><input name="name" required maxlength="80" value="${A.escape(resource?.name||'')}"></div><div class="field"><label>Descripción</label><textarea name="description" maxlength="240">${A.escape(resource?.description||'')}</textarea></div><div class="actions">${editing?'<button type="button" class="btn danger" id="delete-resource">'+A.icon('trash',16)+' Eliminar</button>':''}<button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);
    const form=A.modalRoot.querySelector('#resource-form');
    form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const payload={owner_id:A.state.user.id,type:resource?.type||form.elements.type.value,name:String(form.elements.name.value||'').trim(),description:String(form.elements.description.value||'').trim(),target_cents:null,target_date:null,is_shared:false};if(!payload.name)throw new Error('Indica un nombre.');const result=editing?await A.sb.from('resources').update(payload).eq('id',resource.id).eq('owner_id',A.state.user.id):await A.sb.from('resources').insert(payload);if(result.error)throw result.error;await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});A.toast('Espacio guardado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});
    A.modalRoot.querySelector('#delete-resource')?.addEventListener('click',()=>{A.closeModal();R.delete(resource.id);});
  };
  R.delete=id=>A.ui.confirm({title:'Eliminar espacio',message:'Los movimientos asociados quedarán en la cuenta principal. Los traspasos históricos se conservarán.',confirmLabel:'Eliminar',danger:true,onConfirm:async()=>{await A.sb.from('finance_transactions').update({resource_id:null}).eq('resource_id',id).eq('creator_id',A.state.user.id);const result=await A.sb.from('resources').delete().eq('id',id).eq('owner_id',A.state.user.id);if(result.error)throw result.error;await A.store.load({force:true});A.ui.render({preserveScroll:true});A.toast('Espacio eliminado.');}});
  R.openDetail=id=>{const row=A.store.resourceById(id);if(!row)return;const movements=A.timeline().filter(item=>item.item_type==='transaction'?String(item.resource_id||'')===String(id):String(item.source_resource_id||'')===String(id)||String(item.target_resource_id||'')===String(id)).slice(0,12);A.ui.modal(`<div class="modal-head"><div><h2>${A.escape(row.name)}</h2><p>${row.type==='goal'?'Objetivo':row.type==='folder'?'Carpeta':'Hucha'} · ${A.money(A.resourceBalance(id))}</p></div><button class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="resource-detail-actions"><button class="btn secondary" data-action="resource-contribute" data-id="${id}">${A.icon('plus',16)} Aportar</button><button class="btn secondary" data-action="new-transfer" data-source="${id}">${A.icon('transfer',16)} Mover</button><button class="btn primary" data-action="edit-resource" data-id="${id}">${A.icon('edit',16)} Editar</button></div><section class="card nested-card">${A.ui.sectionTitle('Últimos movimientos','Actividad de este espacio')}${movements.length?`<div class="movement-list">${movements.map(A.transactions.rowMarkup).join('')}</div>`:A.ui.empty('Sin movimientos')}</section>`,{wide:true});};
  R.openTransferForm=preset=>{if(A.state.resources.filter(row=>row.type!=='goal').length<2){A.toast('Necesitas al menos dos huchas o carpetas para mover saldo.',true);return;}A.ui.modal(`<form id="transfer-form" class="stack-form"><div class="modal-head"><div><h2>Mover saldo</h2><p>El traspaso no afecta al saldo total disponible.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div><div class="form-grid two"><div class="field"><label>Origen</label><select name="source" required>${A.state.resources.filter(row=>row.type!=='goal').map(row=>`<option value="${row.id}" ${String(preset?.source||'')===String(row.id)?'selected':''}>${A.escape(row.name)} · ${A.money(A.resourceBalance(row.id))}</option>`).join('')}</select></div><div class="field"><label>Destino</label><select name="target" required>${A.state.resources.filter(row=>row.type!=='goal').map(row=>`<option value="${row.id}">${A.escape(row.name)}</option>`).join('')}</select></div></div><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Concepto</label><input name="concept" required value="Traspaso entre huchas"></div><div class="field"><label>Fecha</label><input name="date" type="date" required value="${A.today()}"></div><div class="actions"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary">Realizar traspaso</button></div></form>`);
    const form=A.modalRoot.querySelector('#transfer-form');if(form.elements.source.options.length>1){const source=form.elements.source.value;const target=[...form.elements.target.options].find(option=>option.value!==source);if(target)form.elements.target.value=target.value;}form.elements.source.addEventListener('change',()=>{if(form.elements.target.value===form.elements.source.value){const option=[...form.elements.target.options].find(item=>item.value!==form.elements.source.value);if(option)form.elements.target.value=option.value;}});
    form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const source=form.elements.source.value;const target=form.elements.target.value;const amount=A.toCents(form.elements.amount.value);if(!source||!target||source===target)throw new Error('Selecciona dos espacios diferentes.');if(amount<=0)throw new Error('Indica un importe válido.');await A.rpc('a2c_v8_create_transfer',{p_source_resource_id:source,p_target_resource_id:target,p_amount_cents:amount,p_concept:String(form.elements.concept.value||'').trim(),p_occurred_on:form.elements.date.value,p_scheduled_id:null});A.store.clearStatistics();await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});A.toast('Traspaso realizado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});
  };
  A.ui.action('select-tool',({data})=>{A.state.tool=data.tool;A.ui.render({preserveScroll:false});});
  A.ui.action('new-resource',()=>R.openForm());A.ui.action('open-resource',({data})=>R.openDetail(data.id));A.ui.action('edit-resource',({data})=>{const row=A.store.resourceById(data.id);A.closeModal();R.openForm(row);});A.ui.action('resource-contribute',({data})=>{const row=A.store.resourceById(data.id);A.closeModal();A.transactions.openForm(null,{kind:'saving',resourceId:data.id,concept:`Aportación a ${row?.name||'hucha'}`});});A.ui.action('new-transfer',({data})=>R.openTransferForm({source:data.source||null}));
  A.ui.registerPage('tools',R.renderTools,R.afterTools);
})();
