(function(){
  'use strict';
  const A=window.A2C;
  const R=A.resources={
    renderTools(){
      const tool=A.state.tool||'resources';
      return `${A.ui.header('Herramientas','Planificación','Huchas, objetivos, presupuestos y programaciones','')}
        <div class="section-tabs"><button class="tab-button ${tool==='resources'?'active':''}" data-tool="resources">Huchas y objetivos</button><button class="tab-button ${tool==='budgets'?'active':''}" data-tool="budgets">Presupuestos</button><button class="tab-button ${tool==='scheduled'?'active':''}" data-tool="scheduled">Programados</button><button class="tab-button ${tool==='fuel'?'active':''}" data-tool="fuel">Combustible</button></div>
        <div id="tool-content">${tool==='resources'?R.render():tool==='budgets'?A.budgets.render():tool==='scheduled'?R.renderScheduled():R.renderFuel()}</div>`;
    },
    render(){
      return `<div class="card-title"><div><h2>Huchas, carpetas y objetivos</h2><p>Organiza el dinero sin perder el saldo general.</p></div><button class="btn primary" id="new-resource">＋ Añadir</button></div>${A.state.resources.length?`<div class="grid grid-2">${A.state.resources.map(resource=>{const balance=A.resourceBalance(resource.id);const goal=Number(resource.target_cents||0);const pct=goal?Math.min(100,Math.max(0,balance/goal*100)):0;return `<article class="card clickable" data-resource="${resource.id}"><div class="card-title"><div><h3>${A.escape(resource.name)}</h3><p>${resource.type==='piggy'?'Hucha':resource.type==='goal'?'Objetivo':'Carpeta'}</p></div><span class="kind-icon saving">${resource.type==='goal'?'◎':resource.type==='folder'?'▣':'◉'}</span></div><div style="font-size:24px;font-weight:800">${A.money(balance)}</div>${goal?`<div class="progress" style="margin-top:10px"><i style="width:${pct}%"></i></div><p class="small muted">${Math.round(pct)}% de ${A.money(goal)}</p>`:''}</article>`;}).join('')}</div>`:A.ui.empty('Crea tu primera hucha, carpeta u objetivo.')}`;
    },
    renderScheduled(){return `<div class="card-title"><div><h2>Movimientos programados</h2><p>Avisos y gastos recurrentes.</p></div><button class="btn primary" id="new-scheduled">＋ Añadir</button></div>${A.state.scheduled.length?`<div class="list">${A.state.scheduled.map(row=>`<div class="list-row"><span class="kind-icon expense">↻</span><div class="list-row-main"><strong>${A.escape(row.concept)}</strong><small>${A.escape(row.frequency||'monthly')} · Próximo ${A.escape(row.next_run||'')}</small></div><div class="list-row-value"><b>${A.money(row.amount_cents)}</b><small>${row.active?'Activo':'Pausado'}</small></div><button class="btn small" data-scheduled="${row.id}">Editar</button></div>`).join('')}</div>`:A.ui.empty('No tienes movimientos programados.')}`;},
    renderFuel(){
      const cutoff=new Date();cutoff.setDate(cutoff.getDate()-29);const rows=A.state.transactions.filter(row=>row.fuel_liters&&new Date(row.occurred_on)>=cutoff);const liters=rows.reduce((sum,row)=>sum+Number(row.fuel_liters||0),0);const total=rows.reduce((sum,row)=>sum+Number(row.amount_cents||0),0);const average=liters?total/100/liters:0;
      return `<div class="card-title"><div><h2>Combustible · últimos 30 días</h2><p>Consumo y precio medio real.</p></div><button class="btn primary" id="new-fuel">⛽ Repostaje</button></div><div class="metrics"><div class="metric-card"><small>PRECIO MEDIO</small><b>${average.toLocaleString('es-ES',{minimumFractionDigits:3,maximumFractionDigits:3})} €/L</b></div><div class="metric-card"><small>LITROS</small><b>${liters.toLocaleString('es-ES',{maximumFractionDigits:2})} L</b></div><div class="metric-card expense"><small>GASTO TOTAL</small><b>${A.money(total)}</b></div><div class="metric-card"><small>REPOSTAJES</small><b>${rows.length}</b></div></div>${rows.length?`<div class="list" style="margin-top:12px">${rows.map(A.transactions.rowMarkup).join('')}</div>`:A.ui.empty('No hay repostajes en los últimos 30 días.')}`;
    },
    bind(){
      if(A.state.page!=='tools')return;
      A.root.querySelectorAll('[data-tool]').forEach(button=>button.addEventListener('click',()=>{A.state.tool=button.dataset.tool;A.ui.render();}));
      A.root.querySelector('#new-resource')?.addEventListener('click',()=>R.openForm());
      A.root.querySelectorAll('[data-resource]').forEach(card=>card.addEventListener('click',()=>R.openDetail(card.dataset.resource)));
      A.root.querySelector('#new-scheduled')?.addEventListener('click',()=>R.openScheduled());
      A.root.querySelectorAll('[data-scheduled]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();R.openScheduled(A.state.scheduled.find(row=>String(row.id)===String(button.dataset.scheduled)));}));
      A.root.querySelector('#new-fuel')?.addEventListener('click',A.transactions.openFuelForm);
      A.root.querySelectorAll('[data-transaction]').forEach(row=>row.addEventListener('click',()=>A.transactions.openDetail(row.dataset.transaction)));
      A.budgets.bind();
    },
    openForm(resource=null){
      const editing=Boolean(resource?.id);A.modal(`<form id="resource-form"><div class="modal-head"><div><h2>${editing?'Editar':'Nuevo'} espacio</h2><p>Organiza una parte de tu dinero.</p></div><button class="modal-close" data-close>×</button></div><div class="field"><label>Tipo</label><select name="type" ${editing?'disabled':''}><option value="piggy" ${resource?.type==='piggy'?'selected':''}>Hucha</option><option value="folder" ${resource?.type==='folder'?'selected':''}>Carpeta</option><option value="goal" ${resource?.type==='goal'?'selected':''}>Objetivo</option></select></div><div class="field"><label>Nombre</label><input name="name" required maxlength="80" value="${A.escape(resource?.name||'')}"></div><div class="field"><label>Descripción</label><textarea name="description">${A.escape(resource?.description||'')}</textarea></div><div class="field" id="goal-target"><label>Objetivo (€)</label><input name="target" inputmode="decimal" value="${resource?.target_cents?Number(resource.target_cents)/100:''}"></div><div class="field"><label>Fecha objetivo</label><input name="target_date" type="date" value="${A.escape(resource?.target_date||'')}"></div><div class="actions">${editing?'<button type="button" class="btn danger" id="delete-resource">Eliminar</button>':''}<button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);
      const form=A.modalRoot.querySelector('#resource-form');const sync=()=>A.modalRoot.querySelector('#goal-target').classList.toggle('hidden',form.elements.type.value!=='goal');form.elements.type.addEventListener('change',sync);sync();
      form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const payload={owner_id:A.state.user.id,type:resource?.type||form.elements.type.value,name:String(form.elements.name.value).trim(),description:String(form.elements.description.value||''),target_cents:form.elements.type.value==='goal'?A.toCents(form.elements.target.value):null,target_date:form.elements.target_date.value||null,is_shared:false};const query=editing?A.sb.from('resources').update(payload).eq('id',resource.id):A.sb.from('resources').insert(payload);const result=await query;if(result.error)throw result.error;await A.refresh(false);A.closeModal();A.ui.render();A.toast('Espacio guardado.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});
      A.modalRoot.querySelector('#delete-resource')?.addEventListener('click',()=>A.ui.confirm({title:'Eliminar espacio',message:'Los movimientos no se borrarán; quedarán en la cuenta principal.',danger:true,confirmLabel:'Eliminar',onConfirm:async()=>{await A.sb.from('finance_transactions').update({resource_id:null}).eq('resource_id',resource.id);const result=await A.sb.from('resources').delete().eq('id',resource.id);if(result.error)throw result.error;await A.refresh(false);A.closeModal();A.ui.render();}}));
    },
    openDetail(id){const resource=A.store.resourceById(id);if(!resource)return;const rows=A.state.transactions.filter(row=>String(row.resource_id||'')===String(id));A.modal(`<div class="modal-head"><div><h2>${A.escape(resource.name)}</h2><p>${resource.type==='goal'?'Objetivo':resource.type==='folder'?'Carpeta':'Hucha'} · ${A.money(A.resourceBalance(id))}</p></div><button class="modal-close" data-close>×</button></div><div class="actions"><button class="btn" id="resource-contribute">＋ Aportar</button><button class="btn" id="resource-edit">Editar</button></div><section class="card" style="margin-top:12px"><div class="card-title"><h3>Movimientos</h3></div>${rows.length?`<div class="list">${rows.map(A.transactions.rowMarkup).join('')}</div>`:A.ui.empty('Todavía no hay movimientos.')}</section>`,true);A.modalRoot.querySelector('#resource-edit').addEventListener('click',()=>{A.closeModal();R.openForm(resource);});A.modalRoot.querySelector('#resource-contribute').addEventListener('click',()=>{A.closeModal();A.transactions.openForm(null,{kind:'saving',concept:`Aportación a ${resource.name}`,resourceId:id});});A.modalRoot.querySelectorAll('[data-transaction]').forEach(row=>row.addEventListener('click',()=>A.transactions.openDetail(row.dataset.transaction)));},
    openScheduled(existing=null){
      A.modal(`<form id="scheduled-form"><div class="modal-head"><div><h2>${existing?'Editar':'Nuevo'} gasto programado</h2><p>Recibirás un aviso antes de la fecha prevista.</p></div><button class="modal-close" data-close>×</button></div><div class="field"><label>Concepto</label><input name="concept" required value="${A.escape(existing?.concept||'')}"></div><div class="field-row"><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required value="${existing?Number(existing.amount_cents)/100:''}"></div><div class="field"><label>Cuenta</label><select name="resource"><option value="">Cuenta principal</option>${A.state.resources.map(resource=>`<option value="${resource.id}" ${String(existing?.source_resource_id||'')===String(resource.id)?'selected':''}>${A.escape(resource.name)}</option>`).join('')}</select></div></div><div class="field-row"><div class="field"><label>Frecuencia</label><select name="frequency"><option value="monthly">Mensual</option><option value="weekly">Semanal</option><option value="daily">Diaria</option></select></div><div class="field"><label>Próxima fecha</label><input name="next_run" type="date" required value="${A.escape(existing?.next_run||A.today())}"></div></div><label class="check-row"><input name="active" type="checkbox" ${existing?.active===false?'':'checked'}><span><b>Programación activa</b><small>Se incluirá en los próximos movimientos.</small></span></label><div class="actions">${existing?'<button type="button" class="btn danger" id="delete-scheduled">Eliminar</button>':''}<button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);
      const form=A.modalRoot.querySelector('#scheduled-form');form.elements.frequency.value=existing?.frequency||'monthly';form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const payload={user_id:A.state.user.id,source_resource_id:form.elements.resource.value||null,concept:String(form.elements.concept.value).trim(),amount_cents:A.toCents(form.elements.amount.value),frequency:form.elements.frequency.value,day_of_month:form.elements.frequency.value==='monthly'?1:null,weekday:form.elements.frequency.value==='weekly'?1:null,next_run:form.elements.next_run.value,active:form.elements.active.checked,payment_method:'bank',updated_at:new Date().toISOString()};if(!payload.concept||payload.amount_cents<=0)throw new Error('Concepto o importe no válido.');const result=existing?await A.sb.from('scheduled_expenses_v66').update(payload).eq('id',existing.id):await A.sb.from('scheduled_expenses_v66').insert(payload);if(result.error)throw result.error;await A.refresh(false);A.closeModal();A.ui.render();A.toast('Programación guardada.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});A.modalRoot.querySelector('#delete-scheduled')?.addEventListener('click',()=>A.ui.confirm({title:'Eliminar programación',message:'No se crearán más movimientos.',danger:true,confirmLabel:'Eliminar',onConfirm:async()=>{const result=await A.sb.from('scheduled_expenses_v66').delete().eq('id',existing.id);if(result.error)throw result.error;await A.refresh(false);A.ui.render();}}));}
  };
  A.ui.registerPage('tools',R.renderTools);
})();
