(function(){
  'use strict';
  const A=window.A2C;
  const S=A.scheduled={};
  S.rowMarkup=row=>{
    const transfer=row.movement_type==='transfer';const source=row.source?.name||A.store.resourceById(row.source_resource_id)?.name||'Cuenta principal';const target=row.target?.name||A.store.resourceById(row.target_resource_id)?.name||'';
    return `<article class="scheduled-row"><span class="movement-icon ${transfer?'neutral':'black'}">${A.icon(transfer?'transfer':'calendar',20)}</span><div class="scheduled-main"><strong>${A.escape(row.concept|| (transfer?'Traspaso programado':'Gasto programado'))}</strong><small>${A.formatDate(row.next_run)} · ${transfer?`${A.escape(source)} → ${A.escape(target)}`:`${A.escape(source)} · ${S.frequencyLabel(row.frequency)}`}</small></div><div class="scheduled-value"><b>${A.money(row.amount_cents)}</b><span>${transfer?'Traspaso':'Gasto'}</span></div><div class="scheduled-actions"><button class="icon-action" data-action="run-scheduled" data-id="${row.id}" aria-label="Registrar ahora">${A.icon('plus',17)}</button><button class="icon-action" data-action="edit-scheduled" data-id="${row.id}" aria-label="Editar">${A.icon('edit',17)}</button></div></article>`;
  };
  S.frequencyLabel=value=>({daily:'Diario',weekly:'Semanal',monthly:'Mensual'}[value]||'Mensual');
  S.render=()=>{
    const rows=A.state.scheduled.slice().sort((a,b)=>String(a.next_run).localeCompare(String(b.next_run)));
    return `${A.ui.sectionTitle('Movimientos pendientes','Programa gastos y movimientos entre huchas','<button class="btn small primary" data-action="new-scheduled">'+A.icon('plus',15)+' Programar</button>')}${rows.length?`<div class="scheduled-list">${rows.map(S.rowMarkup).join('')}</div>`:A.ui.empty('No hay movimientos programados','Crea un gasto periódico o un traspaso entre huchas.')}`;
  };
  S.openForm=existing=>{
    const editing=Boolean(existing?.id);const type=existing?.movement_type||'expense';
    A.ui.modal(`<form id="scheduled-form" class="stack-form"><div class="modal-head"><div><h2>${editing?'Editar':'Programar'} movimiento</h2><p>El aviso se enviará una sola vez por cada fecha programada.</p></div><button type="button" class="modal-close" data-close>${A.icon('close',21)}</button></div>
      <div class="segmented-control"><label><input type="radio" name="movement_type" value="expense" ${type==='expense'?'checked':''}><span>${A.icon('expense',17)} Gasto</span></label><label><input type="radio" name="movement_type" value="transfer" ${type==='transfer'?'checked':''}><span>${A.icon('transfer',17)} Entre huchas</span></label></div>
      <div class="field"><label>Concepto</label><input name="concept" required value="${A.escape(existing?.concept||'')}" placeholder="Ej. Suscripción, seguro o ahorro mensual"></div>
      <div class="form-grid two"><div class="field"><label>Importe (€)</label><input name="amount" inputmode="decimal" required value="${existing?Number(existing.amount_cents)/100:''}"></div><div class="field"><label>Próxima fecha</label><input name="next_run" type="date" required value="${A.escape(existing?.next_run||A.today())}"></div></div>
      <div class="form-grid two"><div class="field"><label id="source-label">Cuenta o hucha</label><select name="source"><option value="">Cuenta principal</option>${A.state.resources.map(resource=>`<option value="${resource.id}" ${String(existing?.source_resource_id||'')===String(resource.id)?'selected':''}>${A.escape(resource.name)}</option>`).join('')}</select></div><div class="field" id="target-field"><label>Hucha de destino</label><select name="target"><option value="">Selecciona destino</option>${A.state.resources.map(resource=>`<option value="${resource.id}" ${String(existing?.target_resource_id||'')===String(resource.id)?'selected':''}>${A.escape(resource.name)}</option>`).join('')}</select></div></div>
      <div class="field"><label>Frecuencia</label><select name="frequency"><option value="monthly">Mensual</option><option value="weekly">Semanal</option><option value="daily">Diaria</option></select></div>
      <label class="option-card"><input name="active" type="checkbox" ${existing?.active===false?'':'checked'}><span class="option-icon">${A.icon('calendar',20)}</span><span><b>Programación activa</b><small>Aparecerá en inicio y podrá avisarte antes de la fecha.</small></span></label>
      <div class="actions">${editing?'<button type="button" class="btn danger" id="delete-scheduled">'+A.icon('trash',16)+' Eliminar</button>':''}<button type="button" class="btn secondary" data-close>Cancelar</button><button type="submit" class="btn primary">Guardar programación</button></div></form>`);
    const form=A.modalRoot.querySelector('#scheduled-form');form.elements.frequency.value=existing?.frequency||'monthly';
    const syncType=()=>{const transfer=form.elements.movement_type.value==='transfer';A.modalRoot.querySelector('#target-field').classList.toggle('hidden',!transfer);A.modalRoot.querySelector('#source-label').textContent=transfer?'Hucha de origen':'Cuenta o hucha';if(transfer&&form.elements.source.value==='')form.elements.source.value=A.state.resources[0]?.id||'';};
    form.querySelectorAll('[name="movement_type"]').forEach(input=>input.addEventListener('change',syncType));syncType();
    form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;A.setBusy(button,true);try{const movementType=form.elements.movement_type.value;const source=form.elements.source.value||null;const target=form.elements.target.value||null;const amount=A.toCents(form.elements.amount.value);const concept=String(form.elements.concept.value||'').trim();if(!concept||amount<=0)throw new Error('Indica un concepto y un importe válidos.');if(movementType==='transfer'){if(!source||!target)throw new Error('Selecciona la hucha de origen y la de destino.');if(source===target)throw new Error('El origen y el destino deben ser diferentes.');}const payload={user_id:A.state.user.id,movement_type:movementType,source_resource_id:source,target_resource_id:movementType==='transfer'?target:null,concept,amount_cents:amount,frequency:form.elements.frequency.value,day_of_month:form.elements.frequency.value==='monthly'?Number(form.elements.next_run.value.slice(-2)):null,weekday:form.elements.frequency.value==='weekly'?new Date(`${form.elements.next_run.value}T12:00:00`).getDay():null,next_run:form.elements.next_run.value,active:form.elements.active.checked,payment_method:'bank',updated_at:new Date().toISOString()};const result=editing?await A.sb.from('scheduled_expenses_v66').update(payload).eq('id',existing.id).eq('user_id',A.state.user.id):await A.sb.from('scheduled_expenses_v66').insert(payload);if(result.error)throw result.error;await A.store.load({force:true});A.closeModal();A.ui.render({preserveScroll:true});A.toast('Programación guardada.');}catch(error){A.toast(error.message,true);A.setBusy(button,false);}});
    A.modalRoot.querySelector('#delete-scheduled')?.addEventListener('click',()=>{A.closeModal();S.delete(existing.id);});
  };
  S.run=id=>A.ui.confirm({title:'Registrar movimiento',message:'Se registrará ahora y la próxima fecha se actualizará automáticamente.',confirmLabel:'Registrar ahora',onConfirm:async()=>{await A.rpc('a2c_v8_run_scheduled',{p_scheduled_id:id});A.store.clearStatistics();await A.store.load({force:true});A.ui.render({preserveScroll:true});A.toast('Movimiento registrado.');}});
  S.delete=id=>A.ui.confirm({title:'Eliminar programación',message:'No se crearán más movimientos para esta programación.',confirmLabel:'Eliminar',danger:true,onConfirm:async()=>{const result=await A.sb.from('scheduled_expenses_v66').delete().eq('id',id).eq('user_id',A.state.user.id);if(result.error)throw result.error;await A.store.load({force:true});A.ui.render({preserveScroll:true});A.toast('Programación eliminada.');}});
  A.ui.action('edit-scheduled',({data})=>S.openForm(A.state.scheduled.find(row=>String(row.id)===String(data.id))));
  A.ui.action('run-scheduled',({data})=>S.run(data.id));
})();
